#!/usr/bin/env node
// Appends one line to memory-bank/dev-log.md after every commit.
// Format: `- [ISO_DATE] HASH | subject | Phase/Type/Scope or (pending-Phase) | files:N (+X/-Y)`
// Never blocks commit (always exits 0).

import { appendFileSync, existsSync, writeFileSync, readFileSync } from 'node:fs';
import { execSync } from 'node:child_process';
import { resolve } from 'node:path';

const LOG = resolve(process.cwd(), 'memory-bank/dev-log.md');

try {
  const hash = execSync('git rev-parse HEAD', { encoding: 'utf8' }).trim();
  const date = execSync('git log -1 --pretty=format:%ad --date=iso-strict', { encoding: 'utf8' }).trim();
  const subject = execSync('git log -1 --pretty=format:%s', { encoding: 'utf8' }).trim();
  // Read full commit message body so Phase/Type/Scope markers placed in body lines are detected.
  const body = execSync('git log -1 --pretty=format:%B', { encoding: 'utf8' }).trim();
  const numstat = execSync('git show --shortstat --format="" HEAD', { encoding: 'utf8' }).trim();
  const filesMatch = numstat.match(/(\d+) files? changed/);
  const insMatch = numstat.match(/(\d+) insertions?\(\+\)/);
  const delMatch = numstat.match(/(\d+) deletions?\(-\)/);
  const files = filesMatch ? filesMatch[1] : '?';
  const ins = insMatch ? insMatch[1] : '0';
  const del = delMatch ? delMatch[1] : '0';

  const phaseMatch = body.match(/Phase:\s*([^\s\/]+)/i);
  const typeMatch = body.match(/Type:\s*([^\s\/]+)/i);
  const scopeMatch = body.match(/Scope:\s*([^\s\/]+)/i);

  let meta;
  if (phaseMatch || typeMatch || scopeMatch) {
    meta = 'Phase=' + (phaseMatch ? phaseMatch[1] : '?')
         + ' | Type=' + (typeMatch ? typeMatch[1] : '?')
         + ' | Scope=' + (scopeMatch ? scopeMatch[1] : '?');
  } else {
    meta = '(pending-Phase)';
  }

  const line = '- [' + date + '] ' + hash.slice(0, 7) + ' | ' + subject + ' | ' + meta + ' | files:' + files + ' (+' + ins + '/-' + del + ')\n';

  if (!existsSync(LOG)) {
    const header = '# Dev Log (auto-generated by .githooks/post-commit)\n\n'
      + '> Single source of truth for commit-level history. Auto-populated on every commit.\n'
      + '> Unlike `progress.md` (human-edited, Phase-aggregated), this file is machine-generated and append-only.\n\n'
      + '## Format\n\n'
      + '`- [ISO_DATE] HASH | subject | Phase=X | Type=Y | Scope=Z | files:N (+X/-Y)`\n\n'
      + 'When a commit lacks `Phase:`, `Type:`, `Scope:` markers, it is recorded as `(pending-Phase)`.\n\n'
      + '## Usage\n\n'
      + '- `npm run dev:pending` -- list all commits without Phase markers\n'
      + '- New Cline session: read this file first to understand what shipped last week\n\n';
    writeFileSync(LOG, header, 'utf8');
  }

  // Self-skip: if working tree already has a row for the current commit hash,
  // we are inside an amend-loop (hook just rewrote the file before commit finalized).
  // Skip to avoid infinite append.
  try {
    const currentContent = readFileSync(LOG, 'utf8');
    if (currentContent.includes(hash.slice(0, 7))) {
      process.exit(0);
    }
  } catch (e) {
    // ignore read errors, proceed to write
  }

  appendFileSync(LOG, line, 'utf8');
} catch (err) {
  console.error('[dev-log] post-commit hook failed:', err.message);
  process.exit(0); // never block commit
}