import fs from 'fs';

const translations = {
  // ===== German (DE) =====
  de: {
    "services.hotformingstressknowhow.section_badge": "Verfahrenstechnik",
    "services.hotformingstressknowhow.title_part1": "Heißumformung & Spannungen",
    "services.hotformingstressknowhow.subtitle": "Die Beherrschung starker Rückfederung und Strukturverzug bei Titan erfordert thermomechanische Modellierung sowie vollständige Vakuum-Spannungsentlastung. So erreichen wir Maßhaltigkeit bei mehrtonnigen Strukturen.",
    "services.hotformingstressknowhow.card1.title": "Thermisches Umformen & Mikrokompensation der Rückfederung",
    "services.hotformingstressknowhow.card1.problem": "Das hohe Festigkeits-Modul-Verhältnis von Titan (Zugfestigkeit 950 MPa vs. Elastizitätsmodul 114 GPa) führt zu extremem Rückfedern während der Kaltumformung, wobei das Material nach dem Lösen der Umformkraft 15-30 Prozent des Biegewinkels elastisch zurückgewinnt. Bei dicken Platten (10-50 mm) ist dieses Rückfedern stark nichtlinear und geometrieabhängig, wodurch konventionelle Überbiegezugaben ungenau werden und kostspielige Maßnacharbeiten verursachen.",
    "services.hotformingstressknowhow.card1.solution": "Lokalisierte Infrarot-Erwärmung (600-800 °C) & Finite-Elemente-Rückfederungsmodellierung",
    "services.hotformingstressknowhow.card1.detail0": "Lokalisierte Infrarot-Heizfelder erwärmen ausschließlich die Biegezone auf 600-800 °C – das optimale Warmumformfenster, in dem die Duktilität um 300 % steigt und die Streckgrenze um 60 % sinkt. Dies reduziert die Rückfederung drastisch und ermöglicht enge Radien ohne Rissbildung.",
    "services.hotformingstressknowhow.card1.detail1": "Finite-Elemente-Analyse (FEA) Rückfederungsvorhersagemodelle simulieren den gesamten Umformzyklus: Aufheizprofil, Kriechumformung während der Haltezeit, elastische Rückstellung während der Abkühlung und endgültige Geometrie – und erzeugen kompensierte Werkzeuggeometrien, die die vorhergesagte Abweichung bereits vor der Umformung des ersten Bauteils ausgleichen.",
    "services.hotformingstressknowhow.card1.detail2": "Iterative Überbiegungskompensation: Der vom FEM-Modell vorhergesagte Rückfederungswinkel wird als automatischer Überbiegungsversatz (typischerweise 3-12 Grad, abhängig von Blechdicke, Biegeradius und Temperatur) in die Abkantpressensteuerung eingespeist, wodurch der Trial-and-Error-Zyklus von 3-5 Iterationen auf einen einzigen validierten Einrichtungsvorgang reduziert wird.",
    "services.hotformingstressknowhow.card1.detail3": "Ergebnis: Winkelgenauigkeit von ±0,5 Grad bei warmgeformten schweren Titanplatten – Eliminierung sekundärer Richtvorgänge und Sicherstellung der Passgenauigkeit mit angrenzenden Strukturbauteilen.",
    "services.hotformingstressknowhow.card2.title": "Vollständige Vakuum-Spannungsarmglühzyklen",
    "services.hotformingstressknowhow.card2.problem": "Das Walzen, Schmieden und Schweißen von schweren Titanplatten führt zu massiven Eigenspannungen durch ungleichmäßige plastische Verformung während der Umformung (Walzspannungen bis zu 60 % der Streckgrenze), thermische Schrumpfspannungen in mehrlagigen Schweißnähten sowie Spannungskonzentrationen an geformten Radienübergängen. Werden diese Eigenspannungen nicht abgebaut, verursachen sie verzögerte Verformungen während der Bearbeitung, Maßabweichungen im Laufe der Zeit sowie unvorhersehbare Leistung unter Tiefsee-Hyperbarbelastung oder zyklischer Ermüdungsbelastung.",
    "services.hotformingstressknowhow.card2.solution": "Mehrfach-Messwert computergesteuerter Vakuumglühofen – über 95 % Spannungsabbau",
    "services.hotformingstressknowhow.card2.detail0": "Vollmaßstab-Vakuumglühofen mit nutzbaren Kammerabmessungen für Bauteile bis zu 12.000 x 4.500 x 4.000 mm. Die gesamte geschweißte Konstruktion wird in einem einzigen thermischen Zyklus spannungsarm geglüht, wodurch lokale oder segmentierte Spannungsentlastungen entfallen.",
    "services.hotformingstressknowhow.card2.detail1": "Computergesteuerte thermische Zyklussteuerung mit einer Gleichmäßigkeit von ±5 °C über die gesamte Charge: Aufheizen auf 540-650 °C mit 50 °C/h, Haltezeit von 1 Stunde pro 25 mm Wanddicke, Abkühlen mit 50 °C/h auf 300 °C, anschließend natürliche Konvektion auf Raumtemperatur – zur Gewährleistung vollständiger Spannungsentspannung ohne thermisch gradientenbedingte Verformung.",
    "services.hotformingstressknowhow.card2.detail2": "Vakuumatmosphäre während des gesamten thermischen Zyklus auf unter 10⁻⁵ mbar gehalten – verhindert jegliche Oberflächenoxidation, Alpha-Case-Bildung oder Verfärbung an den Titanbauteilen, sodass keine chemische Reinigung oder mechanische Entzunderung nach der Entlastung erforderlich ist.",
    "services.hotformingstressknowhow.card2.detail3": "Ergebnis: Über 95 Prozent der verbleibenden Schweiß- und Umformspannungen eliminiert – verifiziert durch Trennverfahren und Dehnungsmessung gemäß ASTM E837. Die Strukturen behalten ihre Maßstabilität bei nachfolgender Bearbeitung, Transport, Montage sowie bei thermischen Zyklen im Einsatz unter Tiefsee-Hyperbarbedingungen oder kryogenen Bedingungen.",
    "services.hotformingstressknowhow.relief_knowhow": "Spannungsentlastungs-Know-how"
  },
  // ===== French (FR) =====
  fr: {
    "services.hotformingstressknowhow.section_badge": "Ingénierie des procédés",
    "services.hotformingstressknowhow.title_part1": "Formage à chaud & Contrainte",
    "services.hotformingstressknowhow.subtitle": "La maîtrise du retour élastique du titane lourd et du gauchissement structurel nécessite une modélisation thermomécanique et un traitement de détensionnement sous vide à grande échelle. Voici comment nous obtenons la stabilité dimensionnelle sur des structures de plusieurs tonnes.",
    "services.hotformingstressknowhow.card1.title": "Formage thermique et micro-compensation du retour élastique",
    "services.hotformingstressknowhow.card1.problem": "Le rapport résistance/module élevé du titane (RUT 950 MPa contre module d'élasticité 114 GPa) provoque un retour élastique extrême lors du formage à froid, où le matériau récupère élastiquement 15 à 30 % de l'angle de pliage après le relâchement de la charge de formage. Sur les plaques épaisses (10-50 mm), ce retour élastique est hautement non linéaire et dépend de la géométrie, rendant les surépaisseurs de pliage conventionnelles imprécises et entraînant des reprises dimensionnelles coûteuses.",
    "services.hotformingstressknowhow.card1.solution": "Chauffage infrarouge localisé (600-800 °C) et modélisation du retour élastique par éléments finis",
    "services.hotformingstressknowhow.card1.detail0": "Les réseaux de chauffage infrarouge localisés ciblent exclusivement la zone de pliage, portant la température du titane à 600-800 °C, soit la fenêtre optimale de formage à chaud où la ductilité augmente de 300 % et la limite d'élasticité chute de 60 %, réduisant considérablement l'amplitude du retour élastique et permettant des pliages à rayon serré sans fissuration.",
    "services.hotformingstressknowhow.card1.detail1": "Les modèles de prédiction du retour élastique par analyse par éléments finis (FEA) simulent le cycle complet de formage : profil de chauffage, formage par fluage pendant la période de maintien, récupération élastique lors du refroidissement et géométrie finale - générant des géométries d'outillage compensées qui contrent le décalage prédit avant la formation de la première pièce.",
    "services.hotformingstressknowhow.card1.detail2": "Compensation itérative de la sur-cintrage : l'angle de retour élastique prédit par le modèle EF est transmis au contrôleur de la presse plieuse sous forme de décalage de sur-cintrage automatisé (généralement de 3 à 12 degrés selon l'épaisseur de la tôle, le rayon de cintrage et la température), réduisant le cycle d'essais-erreurs de 3 à 5 itérations à une seule configuration validée.",
    "services.hotformingstressknowhow.card1.detail3": "Résultat : précision angulaire de ±0,5 degré sur les plaques épaisses en titane formées à chaud - éliminant les opérations de redressage secondaire et garantissant la conformité d'assemblage avec les composants structurels correspondants.",
    "services.hotformingstressknowhow.card2.title": "Cycles thermiques de détensionnement sous vide à pleine échelle",
    "services.hotformingstressknowhow.card2.problem": "Le laminage, le forgeage et le soudage de plaques épaisses en titane génèrent d'importantes contraintes résiduelles dues à la déformation plastique non uniforme lors du formage (contraintes de laminage atteignant 60 % de la limite d'élasticité), aux contraintes de contraction thermique dans les cordons de soudure multipasses, ainsi qu'aux concentrations de contraintes au niveau des transitions de rayon formées. Si elles ne sont pas relaxées, ces contraintes internes provoquent des déformations différées lors de l'usinage, une dérive dimensionnelle dans le temps, et des performances imprévisibles sous des charges hyperbares en eaux profondes ou en fatigue cyclique.",
    "services.hotformingstressknowhow.card2.solution": "Four Électrique Informatisé de Recuit sous Vide - Élimination des Contraintes à plus de 95 %",
    "services.hotformingstressknowhow.card2.detail0": "Four de recuit sous vide à grande échelle avec des dimensions de chambre utiles pouvant accueillir des composants jusqu'à 12 000 x 4 500 x 4 000 mm. L'ensemble de la structure fabriquée subit un traitement de détensionnement en un seul cycle thermique, éliminant ainsi le besoin de détensionnement localisé ou segmenté.",
    "services.hotformingstressknowhow.card2.detail1": "Contrôle informatisé du cycle thermique avec une uniformité de ±5 °C sur l'ensemble de la charge : montée en température à 540-650 °C à raison de 50 °C/h, maintien d'une heure par tranche de 25 mm d'épaisseur, refroidissement à 50 °C/h jusqu'à 300 °C, puis convection naturelle jusqu'à la température ambiante – garantissant une relaxation complète des contraintes sans déformation induite par gradient thermique.",
    "services.hotformingstressknowhow.card2.detail2": "L'atmosphère sous vide est maintenue à moins de 10⁻⁵ mbar pendant tout le cycle thermique, empêchant toute oxydation de surface, formation d'alpha-case ou décoloration sur les composants en titane, éliminant ainsi la nécessité d'un nettoyage chimique post-traitement ou d'un décapage mécanique.",
    "services.hotformingstressknowhow.card2.detail3": "Résultat : plus de 95 % des contraintes résiduelles de soudage et de formage éliminées - vérifié par sectionnement et mesure par jauges de contrainte selon ASTM E837. Les structures conservent leur stabilité dimensionnelle lors des opérations ultérieures d'usinage, de transport, d'installation et des cycles thermiques en service dans des conditions hyperbares en eaux profondes ou cryogéniques.",
    "services.hotformingstressknowhow.relief_knowhow": "Savoir-faire en relaxation des contraintes"
  },
  // ===== Spanish (ES) =====
  es: {
    "services.hotformingstressknowhow.section_badge": "Ingeniería de Procesos",
    "services.hotformingstressknowhow.title_part1": "Conformado en Caliente y Alivio de Tensiones",
    "services.hotformingstressknowhow.subtitle": "Para superar el rebote elástico del titanio pesado y la deformación estructural, se requiere modelado termomecánico y alivio de tensiones al vacío a escala real. Así logramos la estabilidad dimensional en estructuras de varias toneladas.",
    "services.hotformingstressknowhow.card1.title": "Conformado Térmico y Microcompensación por Recuperación Elástica",
    "services.hotformingstressknowhow.card1.problem": "La alta relación resistencia-módulo del titanio (UTS 950 MPa frente a módulo elástico 114 GPa) provoca un retorno elástico extremo durante el conformado en frío, donde el material recupera elásticamente entre un 15 y un 30 por ciento del ángulo de curvatura después de liberar la carga de conformado. En placas gruesas (10-50 mm), este retorno elástico es altamente no lineal y dependiente de la geometría, lo que hace que las tolerancias convencionales de sobrecurvatura sean inexactas y provoque costosos retrabajos dimensionales.",
    "services.hotformingstressknowhow.card1.solution": "Calentamiento Infrarrojo Localizado (600-800 °C) y Modelado de Recuperación Elástica por Elementos Finitos",
    "services.hotformingstressknowhow.card1.detail0": "Los conjuntos de calentamiento infrarrojo localizado se dirigen exclusivamente a la zona de curvatura, elevando la temperatura del titanio a 600-800 °C, la ventana óptima de conformado en caliente donde la ductilidad aumenta un 300 % y el límite elástico disminuye un 60 %, reduciendo drásticamente la magnitud del retorno elástico y permitiendo curvaturas de radio estrecho sin agrietamiento.",
    "services.hotformingstressknowhow.card1.detail1": "Los modelos de predicción de recuperación elástica mediante Análisis de Elementos Finitos (FEA) simulan el ciclo completo de conformado: perfil de calentamiento, conformado por fluencia durante el período de remojo, recuperación elástica durante el enfriamiento y geometría final, generando geometrías de herramienta compensadas que contrarrestan la desviación prevista antes de conformar la primera pieza.",
    "services.hotformingstressknowhow.card1.detail2": "Compensación iterativa de sobrecurvatura: el ángulo de recuperación elástica previsto por el modelo de elementos finitos (FEA) se introduce en el controlador de la plegadora como un desplazamiento automático de sobrecurvatura (generalmente de 3 a 12 grados, según el espesor de la chapa, el radio de curvatura y la temperatura), reduciendo el ciclo de prueba y error de 3 a 5 iteraciones a una única configuración validada.",
    "services.hotformingstressknowhow.card1.detail3": "Resultado: precisión angular de ±0.5 grados en placas pesadas de titanio conformadas en caliente, eliminando operaciones secundarias de enderezamiento y garantizando el cumplimiento del ajuste con componentes estructurales acoplados.",
    "services.hotformingstressknowhow.card2.title": "Ciclos Térmicos Completos de Alivio de Tensiones al Vacío",
    "services.hotformingstressknowhow.card2.problem": "Las operaciones de laminado, forjado y soldadura de placas gruesas de titanio generan tensiones residuales masivas debido a la deformación plástica no uniforme durante el conformado (tensiones de laminado de hasta el 60 % del límite elástico), tensiones por contracción térmica en cordones de soldadura de múltiples pasadas y concentración de tensiones en transiciones de radios conformados. Si no se alivian, estas tensiones internas provocan distorsión retardada durante el mecanizado, desviación dimensional con el tiempo y un rendimiento impredecible bajo cargas de fatiga cíclica o hiperbárica en aguas profundas.",
    "services.hotformingstressknowhow.card2.solution": "Horno de Recocido al Vacío Computarizado Multímetro - Eliminación de Tensiones del 95 por ciento o más",
    "services.hotformingstressknowhow.card2.detail0": "Horno de recocido al vacío a escala real con dimensiones de cámara útil que alberga componentes de hasta 12.000 x 4.500 x 4.000 mm. Toda la estructura fabricada se somete a un alivio de tensiones en un solo ciclo térmico, eliminando la necesidad de alivio de tensiones localizado o segmentado.",
    "services.hotformingstressknowhow.card2.detail1": "Control computarizado del ciclo térmico con uniformidad de ±5 °C en toda la carga: rampa de 540 a 650 °C a 50 °C/hora, remojo de 1 hora por cada 25 mm de espesor, enfriamiento a 50 °C/hora hasta 300 °C, luego convección natural hasta temperatura ambiente, garantizando una relajación completa de tensiones sin distorsión inducida por gradientes térmicos.",
    "services.hotformingstressknowhow.card2.detail2": "La atmósfera de vacío se mantiene por debajo de 10⁻⁵ mbar durante todo el ciclo térmico, lo que evita cualquier oxidación superficial, formación de capa alfa o decoloración en los componentes de titanio, eliminando la necesidad de limpieza química posterior o eliminación mecánica de incrustaciones.",
    "services.hotformingstressknowhow.card2.detail3": "Resultado: se elimina más del 95 por ciento de las tensiones residuales de soldadura y conformado, verificado mediante seccionado y medición con galgas extensométricas según ASTM E837. Las estructuras mantienen la estabilidad dimensional durante el mecanizado posterior, transporte, instalación y ciclos térmicos en servicio en condiciones hiperbáricas de aguas profundas o criogénicas.",
    "services.hotformingstressknowhow.relief_knowhow": "Conocimiento en Alivio de Tensiones"
  },
  // ===== Portuguese (PT) =====
  pt: {
    "services.hotformingstressknowhow.section_badge": "Engenharia de Processos",
    "services.hotformingstressknowhow.title_part1": "Conformação a Quente & Tensão",
    "services.hotformingstressknowhow.subtitle": "Superar o retorno elástico do titânio pesado e o empenamento estrutural requer modelagem termomecânica e alívio de tensões a vácuo em escala real. Veja como alcançamos estabilidade dimensional em estruturas de várias toneladas.",
    "services.hotformingstressknowhow.card1.title": "Conformação Térmica e Microcompensação de Retorno Elástico",
    "services.hotformingstressknowhow.card1.problem": "A alta relação resistência-módulo do titânio (UTS 950 MPa vs. módulo elástico 114 GPa) causa retorno elástico extremo durante a conformação a frio — onde o material recupera elasticamente 15-30% do ângulo de curvatura após a liberação da carga de conformação. Em chapas grossas (10-50 mm), este retorno elástico é altamente não linear e dependente da geometria, tornando imprecisas as tolerâncias convencionais de sobrecurvatura e causando retrabalho dimensional custoso.",
    "services.hotformingstressknowhow.card1.solution": "Aquecimento Infravermelho Localizado (600-800°C) e Modelagem de Retorno Elástico por Elementos Finitos",
    "services.hotformingstressknowhow.card1.detail0": "Matrizes de aquecimento infravermelho localizado visam exclusivamente a zona de curvatura, elevando a temperatura do titânio para 600-800°C — a janela ideal de conformação a quente onde a ductilidade aumenta em 300% e o limite de escoamento cai 60%, reduzindo drasticamente a magnitude do retorno elástico e permitindo curvaturas de raio apertado sem trincas.",
    "services.hotformingstressknowhow.card1.detail1": "Modelos de previsão de retorno elástico por Análise de Elementos Finitos (FEA) simulam o ciclo completo de conformação: perfil de aquecimento, conformação por fluência durante o período de saturação, recuperação elástica durante o resfriamento e geometria final — gerando geometrias de ferramenta compensadas que contrapõem o desvio previsto antes da primeira peça ser conformada.",
    "services.hotformingstressknowhow.card1.detail2": "Compensação iterativa de sobrecurvatura: o ângulo de retorno elástico previsto pelo modelo FEA é alimentado no controlador da prensa dobradeira como um deslocamento automático de sobrecurvatura (tipicamente 3-12° dependendo da espessura da chapa, raio de curvatura e temperatura), reduzindo o ciclo de tentativa e erro de 3-5 iterações para uma única configuração validada.",
    "services.hotformingstressknowhow.card1.detail3": "Resultado: precisão angular de ±0,5° em chapas pesadas de titânio conformadas a quente — eliminando operações secundárias de endireitamento e garantindo conformidade de ajuste com componentes estruturais adjacentes.",
    "services.hotformingstressknowhow.card2.title": "Ciclos Térmicos de Alívio de Tensões a Vácuo em Escala Real",
    "services.hotformingstressknowhow.card2.problem": "As operações de laminação, forjamento e soldagem de chapas grossas de titânio introduzem tensões residuais massivas — decorrentes da deformação plástica não uniforme durante a conformação (tensões de laminação de até 60% do escoamento), tensões de contração térmica em cordões de solda multipasses e concentração de tensão nas transições de raio conformado. Se não aliviadas, estas tensões internas causam distorção retardada durante a usinagem, desvio dimensional ao longo do tempo e desempenho imprevisível sob carga hiperbárica em águas profundas ou fadiga cíclica.",
    "services.hotformingstressknowhow.card2.solution": "Forno de Recozimento a Vácuo Computerizado Multímetro — Eliminação de Tensões acima de 95%",
    "services.hotformingstressknowhow.card2.detail0": "Forno de recozimento a vácuo em escala real com dimensões úteis de câmara que acomodam componentes de até 12.000 x 4.500 x 4.000 mm — toda a estrutura fabricada é aliviada de tensões em um único ciclo térmico, eliminando a necessidade de alívio localizado ou segmentado.",
    "services.hotformingstressknowhow.card2.detail1": "Controle computadorizado do ciclo térmico com uniformidade de ±5°C em toda a carga: rampa para 540-650°C a 50°C/hora, saturação por 1 hora a cada 25 mm de espessura, resfriamento a 50°C/hora até 300°C, depois convecção natural até temperatura ambiente — garantindo relaxamento completo de tensões sem distorção induzida por gradiente térmico.",
    "services.hotformingstressknowhow.card2.detail2": "Atmosfera de vácuo mantida a ≤10⁻⁵ mbar durante todo o ciclo térmico — prevenindo qualquer oxidação superficial, formação de camada alfa ou descoloração nos componentes de titânio, eliminando a necessidade de limpeza química pós-alívio ou remoção mecânica de incrustações.",
    "services.hotformingstressknowhow.card2.detail3": "Resultado: mais de 95% das tensões residuais de soldagem e conformação eliminadas — verificado por seccionamento e medição com extensômetros conforme ASTM E837. As estruturas mantêm estabilidade dimensional através da usinagem subsequente, transporte, instalação e ciclos térmicos em serviço sob condições hiperbáricas de águas profundas ou criogênicas.",
    "services.hotformingstressknowhow.relief_knowhow": "Know-How em Alívio de Tensões"
  },
  // ===== Italian (IT) =====
  it: {
    "services.hotformingstressknowhow.section_badge": "Ingegneria di Processo",
    "services.hotformingstressknowhow.title_part1": "Formatura a caldo e tensioni",
    "services.hotformingstressknowhow.subtitle": "Per superare il ritorno elastico del titanio pesante e la deformazione strutturale sono necessari modellazione termo-meccanica e distensione sotto vuoto su scala reale. Ecco come otteniamo stabilità dimensionale su strutture di diverse tonnellate.",
    "services.hotformingstressknowhow.card1.title": "Formatura Termica e Microcompensazione del Ritorno Elastico",
    "services.hotformingstressknowhow.card1.problem": "L'elevato rapporto resistenza-modulo del titanio (UTS 950 MPa vs. modulo elastico 114 GPa) provoca un estremo ritorno elastico durante la formatura a freddo, dove il materiale recupera elasticamente il 15-30% dell'angolo di piega dopo il rilascio del carico di formatura. Su lamiere spesse (10-50 mm), questo ritorno elastico è altamente non lineare e dipendente dalla geometria, rendendo imprecisi i sovrametodi convenzionali di compensazione e causando costose rilavorazioni dimensionali.",
    "services.hotformingstressknowhow.card1.solution": "Riscaldamento a infrarossi localizzato (600-800°C) e modellazione del ritorno elastico tramite elementi finiti",
    "services.hotformingstressknowhow.card1.detail0": "Gli array di riscaldamento a infrarossi localizzati colpiscono esclusivamente la zona di piegatura, portando la temperatura del titanio a 600-800°C, la finestra ottimale per la formatura a caldo in cui la duttilità aumenta del 300% e il carico di snervamento diminuisce del 60%, riducendo drasticamente l'entità del ritorno elastico e consentendo piegature a raggio stretto senza cricche.",
    "services.hotformingstressknowhow.card1.detail1": "I modelli di previsione del ritorno elastico tramite Analisi agli Elementi Finiti (FEA) simulano l'intero ciclo di formatura: profilo termico, formatura per scorrimento viscoso durante il periodo di mantenimento, recupero elastico durante il raffreddamento e geometria finale, generando geometrie utensile compensate che contrastano lo scostamento previsto prima della formatura del primo pezzo.",
    "services.hotformingstressknowhow.card1.detail2": "Compensazione iterativa della sovrappiegatura: l'angolo di ritorno elastico previsto dal modello FEM viene inserito nel controllo della pressa piegatrice come offset automatico di sovrappiegatura (tipicamente 3-12 gradi in funzione dello spessore della lamiera, del raggio di piega e della temperatura), riducendo il ciclo di tentativi ed errori da 3-5 iterazioni a una singola configurazione validata.",
    "services.hotformingstressknowhow.card1.detail3": "Risultato: precisione angolare di ±0,5 gradi su piastre pesanti in titanio formate a caldo, eliminando le operazioni secondarie di raddrizzatura e garantendo la conformità di accoppiamento con i componenti strutturali corrispondenti.",
    "services.hotformingstressknowhow.card2.title": "Cicli termici di distensione sotto vuoto a piena scala",
    "services.hotformingstressknowhow.card2.problem": "Le operazioni di laminazione, forgiatura e saldatura di lamiere spesse in titanio introducono enormi tensioni residue dovute a deformazioni plastiche non uniformi durante la formatura (tensioni di laminazione fino al 60% del carico di snervamento), tensioni da contrazione termica nei cordoni di saldatura multi-pass e concentrazione di tensioni nelle transizioni di raggio formate. Se non vengono eliminate, queste tensioni interne causano distorsioni ritardate durante la lavorazione meccanica, derive dimensionali nel tempo e prestazioni imprevedibili sotto carichi iperbarici in acque profonde o a fatica ciclica.",
    "services.hotformingstressknowhow.card2.solution": "Forno di Ricottura Sottovuoto Computerizzato Multi-Metro - Eliminazione delle Tensioni al 95% e oltre",
    "services.hotformingstressknowhow.card2.detail0": "Forno di ricottura sottovuoto a grandezza naturale con dimensioni utili della camera in grado di ospitare componenti fino a 12.000 x 4.500 x 4.000 mm; l'intera struttura fabbricata viene distesa in un unico ciclo termico, eliminando la necessità di distensione localizzata o segmentata.",
    "services.hotformingstressknowhow.card2.detail1": "Controllo computerizzato del ciclo termico con uniformità di ±5°C su tutto il carico: rampa a 540-650°C a 50°C/ora, mantenimento per 1 ora ogni 25 mm di spessore, raffreddamento a 50°C/ora fino a 300°C, quindi convezione naturale a temperatura ambiente – garantendo il completo rilassamento delle tensioni senza distorsioni indotte da gradienti termici.",
    "services.hotformingstressknowhow.card2.detail2": "Vuoto atmosferico mantenuto al di sotto di 10⁻⁵ mbar per l'intero ciclo termico, prevenendo qualsiasi ossidazione superficiale, formazione di alfa-case o scolorimento sui componenti in titanio, eliminando la necessità di pulizia chimica post-ricottura o rimozione meccanica delle incrostazioni.",
    "services.hotformingstressknowhow.card2.detail3": "Risultato: oltre il 95 percento delle tensioni residue di saldatura e formatura eliminate - verificato tramite sezionamento e misurazione con estensimetri secondo ASTM E837. Le strutture mantengono la stabilità dimensionale durante le successive lavorazioni meccaniche, il trasporto, l'installazione e i cicli termici in servizio in condizioni iperbariche di acque profonde o criogeniche.",
    "services.hotformingstressknowhow.relief_knowhow": "Competenza nella Distensione"
  },
  // ===== Korean (KO) =====
  ko: {
    "services.hotformingstressknowhow.section_badge": "공정 엔지니어링",
    "services.hotformingstressknowhow.title_part1": "열간 성형 및 응력",
    "services.hotformingstressknowhow.subtitle": "중량 티타늄 스프링백 및 구조 뒤틀림을 극복하려면 열-기계적 모델링과 실물 크기 진공 응력 제거가 필요합니다. 다음은 다중 톤 구조물에서 치수 안정성을 달성하는 방법입니다.",
    "services.hotformingstressknowhow.card1.title": "열간 성형 및 스프링백 미세 보정",
    "services.hotformingstressknowhow.card1.problem": "티타늄의 높은 강도-탄성계수 비율(인장강도 950 MPa 대 탄성계수 114 GPa)은 냉간 성형 시 극심한 스프링백을 유발하며, 성형 하중이 제거된 후 재료가 굽힘 각도의 15~30%를 탄성 회복합니다. 후판(10~50mm)의 경우 이러한 스프링백은 고도로 비선형적이고 형상에 의존적이어서 기존의 오버벤드 여유분이 부정확해지고 비용이 많이 드는 치수 재작업이 발생합니다.",
    "services.hotformingstressknowhow.card1.solution": "국부 적외선 가열(600-800°C) 및 유한요소 스프링백 모델링",
    "services.hotformingstressknowhow.card1.detail0": "국소 적외선 가열 어레이가 굽힘 영역에만 집중되어 티타늄 온도를 600~800°C로 상승시킵니다. 이는 최적의 열간 성형 온도 구간으로, 연성이 300% 증가하고 항복 강도가 60% 감소하여 스프링백(spring-back) 크기를 획기적으로 줄이고 균열 없이 급곡률 굽힘을 가능하게 합니다.",
    "services.hotformingstressknowhow.card1.detail1": "유한요소해석(FEA) 스프링백 예측 모델은 전체 성형 사이클(가열 프로파일, 유지 시간 중 크리프 성형, 냉각 중 탄성 회복, 최종 형상)을 시뮬레이션하여, 첫 부품 성형 전에 예측된 오프셋을 상쇄하는 보정된 금형 형상을 생성합니다.",
    "services.hotformingstressknowhow.card1.detail2": "반복적 오버벤드 보정: FEA 모델이 예측한 스프링백 각도가 프레스 브레이크 컨트롤러에 자동 오버벤드 오프셋(일반적으로 판재 두께, 굽힘 반경 및 온도에 따라 3~12도)으로 입력되어, 시행착오 사이클을 3~5회에서 단일 검증된 셋업으로 줄입니다.",
    "services.hotformingstressknowhow.card1.detail3": "결과: 열간 성형된 두꺼운 티타늄 판재에 대해 ±0.5도의 각도 정밀도 확보 - 2차 교정 작업 제거 및 결합 구조 부재와의 조립 적합성 보장",
    "services.hotformingstressknowhow.card2.title": "완전 진공 응력 제거 열처리 사이클",
    "services.hotformingstressknowhow.card2.problem": "중후판 티타늄의 압연, 단조 및 용접 작업 시, 성형 중 불균일 소성 변형으로 인한 대규모 잔류 응력(항복 강도의 최대 60%에 달하는 압연 응력), 다층 용접부의 열 수축 응력, 그리고 성형 반경 전이부의 응력 집중이 발생합니다. 이러한 고정 응력이 제거되지 않으면 가공 중 지연 변형, 시간 경과에 따른 치수 변화, 심해 고압 또는 반복 피로 하중 하에서 예측 불가능한 성능을 초래합니다.",
    "services.hotformingstressknowhow.card2.solution": "멀티미터 전산화 진공 어닐링로 - 95% 이상 응력 제거",
    "services.hotformingstressknowhow.card2.detail0": "가용 챔버 치수가 최대 12,000 x 4,500 x 4,000mm의 부품을 수용할 수 있는 풀 스케일 진공 소둔로로, 전체 제조 구조물이 단일 열처리 사이클에서 응력 제거되어 국부적 또는 분할 응력 제거가 필요 없습니다.",
    "services.hotformingstressknowhow.card2.detail1": "전체 작업물에 대해 ±5°C 균일도를 유지하는 전산화된 열사이클 제어: 시간당 50°C 속도로 540~650°C까지 승온, 두께 25mm당 1시간 유지, 시간당 50°C 속도로 300°C까지 냉각 후 상온까지 자연 대류 냉각 - 열구배로 인한 변형 없이 완전한 응력 완화 보장",
    "services.hotformingstressknowhow.card2.detail2": "진공 분위기는 전체 열처리 사이클 동안 10의 -5제곱 밀리바 미만으로 유지되어 티타늄 부품의 표면 산화, 알파 케이스 형성 또는 변색을 방지하므로, 후처리 화학 세척이나 기계적 스케일 제거가 필요하지 않습니다.",
    "services.hotformingstressknowhow.card2.detail3": "결과: 잔류 용접 및 성형 응력의 95% 이상 제거됨 - ASTM E837에 따른 절단 및 스트레인 게이지 측정으로 검증됨. 구조물은 심해 고압 또는 극저온 조건에서 후속 가공, 운송, 설치 및 운전 중 열 사이클링을 거쳐도 치수 안정성을 유지함.",
    "services.hotformingstressknowhow.relief_knowhow": "응력 제거 노하우"
  },
  // ===== Dutch (NL) =====
  nl: {
    "services.hotformingstressknowhow.section_badge": "Procesengineering",
    "services.hotformingstressknowhow.title_part1": "Warmvormen & Spanning",
    "services.hotformingstressknowhow.subtitle": "Het overwinnen van zware titanium-veerterugslag en structurele kromtrekking vereist thermomechanische modellering en volledige vacuümontspanning. Hier is hoe we dimensionale stabiliteit bereiken bij constructies van meerdere tonnen.",
    "services.hotformingstressknowhow.card1.title": "Thermisch vormen & microcompensatie voor terugvering",
    "services.hotformingstressknowhow.card1.problem": "De hoge sterkte-modulusverhouding van titanium (UTS 950 MPa versus elasticiteitsmodulus 114 GPa) veroorzaakt extreme terugvering tijdens koudvormen, waarbij het materiaal na het loslaten van de vormkracht 15-30 procent van de buighoek elastisch herstelt. Bij dikke platen (10-50 mm) is deze terugvering sterk niet-lineair en geometrieafhankelijk, waardoor conventionele overbuigtoeslagen onnauwkeurig zijn en kostbare maatcorrecties nodig zijn.",
    "services.hotformingstressknowhow.card1.solution": "Gelokaliseerde infraroodverwarming (600-800°C) & Eindige-elementenmodellering van terugvering",
    "services.hotformingstressknowhow.card1.detail0": "Gelokaliseerde infraroodverwarmingsarrays richten zich uitsluitend op het buiggebied, waardoor de titaniumtemperatuur stijgt tot 600-800°C, het optimale warmvormvenster waarin de ductiliteit met 300 procent toeneemt en de vloeigrens met 60 procent daalt. Dit vermindert de mate van terugvering drastisch en maakt bochten met een kleine straal mogelijk zonder scheurvorming.",
    "services.hotformingstressknowhow.card1.detail1": "Eindige-elementenanalyse (FEA) terugveringsvoorspellingsmodellen simuleren de volledige vormcyclus: het verwarmingsprofiel, kruipvorming tijdens de weekperiode, elastisch herstel tijdens het afkoelen en de uiteindelijke geometrie. Hieruit worden gecompenseerde gereedschapsgeometrieën gegenereerd die de voorspelde afwijking tegengaan voordat het eerste onderdeel wordt gevormd.",
    "services.hotformingstressknowhow.card1.detail2": "Iteratieve overbuigcompensatie: de door het FEA-model voorspelde terugveringhoek wordt als geautomatiseerde overbuigcorrectie (doorgaans 3-12 graden, afhankelijk van plaatdikte, buigradius en temperatuur) ingevoerd in de persrembesturing, waardoor de trial-and-error-cyclus wordt teruggebracht van 3-5 iteraties naar één gevalideerde instelling.",
    "services.hotformingstressknowhow.card1.detail3": "Resultaat: hoeknauwkeurigheid van ±0,5 graad op warmgevormde zware titaniumplaten - elimineert secundaire richtbewerkingen en garandeert pasvormconformiteit met bijbehorende constructiecomponenten",
    "services.hotformingstressknowhow.card2.title": "Volledige vacuüm-spanningsontlastende thermische cycli",
    "services.hotformingstressknowhow.card2.problem": "Het walsen, smeden en lassen van zware titaniumplaten introduceert aanzienlijke restspanningen door niet-uniforme plastische vervorming tijdens het vormen (walsspanningen tot 60% van de vloeigrens), thermische krimpspanningen in meerlaagse lasnaden en spanningsconcentraties bij gevormde radiusovergangen. Indien niet ontlast, veroorzaken deze ingesloten spanningen vertraagde vervorming tijdens bewerking, dimensionale verschuiving na verloop van tijd en onvoorspelbare prestaties onder diepzee-hyperbare of cyclische vermoeiingsbelasting.",
    "services.hotformingstressknowhow.card2.solution": "Geautomatiseerde Multimeter Vacuüm Gloeioven - 95 procent of meer spanningseliminatie",
    "services.hotformingstressknowhow.card2.detail0": "Volledige vacuüm gloeioven met bruikbare kamerafmetingen voor componenten tot 12.000 x 4.500 x 4.000 mm. De volledige gelaste constructie wordt in één enkele thermische cyclus spanningsvrij gegloeid, waardoor lokale of gesegmenteerde spanningsontlasting niet nodig is.",
    "services.hotformingstressknowhow.card2.detail1": "Geautomatiseerde thermische cyclusregeling met een uniformiteit van ±5°C over de volledige lading: opwarmen naar 540-650°C met 50°C/uur, inweken gedurende 1 uur per 25 mm dikte, afkoelen met 50°C/uur tot 300°C, daarna natuurlijke convectie tot kamertemperatuur – wat zorgt voor volledige spanningsontspanning zonder vervorming door thermische gradiënten.",
    "services.hotformingstressknowhow.card2.detail2": "Vacuümatmosfeer gedurende de gehele thermische cyclus gehandhaafd op ≤10⁻⁵ mbar, waardoor elke oppervlakteoxidatie, alphahuidvorming of verkleuring op de titaniumcomponenten wordt voorkomen. Dit elimineert de noodzaak voor nabehandeling chemische reiniging of mechanische ontzouting.",
    "services.hotformingstressknowhow.card2.detail3": "Resultaat: meer dan 95 procent van de resterende las- en vormspanningen geëlimineerd - geverifieerd door doorsnijden en rekstrookmeting volgens ASTM E837. Constructies behouden dimensionale stabiliteit tijdens daaropvolgende bewerking, transport, installatie en thermische cycli onder diepzee-hyperbare of cryogene omstandigheden.",
    "services.hotformingstressknowhow.relief_knowhow": "Spanningsontlastingskennis"
  },
  // ===== Polish (PL) =====
  pl: {
    "services.hotformingstressknowhow.section_badge": "Inżynieria procesu",
    "services.hotformingstressknowhow.title_part1": "Formowanie na gorąco i odprężanie",
    "services.hotformingstressknowhow.subtitle": "Pokonanie silnego odrzutu tytanu oraz odkształceń strukturalnych wymaga modelowania termomechanicznego i pełnowymiarowego odprężania próżniowego. Oto jak osiągamy stabilność wymiarową w konstrukcjach wielotonowych.",
    "services.hotformingstressknowhow.card1.title": "Formowanie termiczne i mikrokompensacja odbicia sprężystego",
    "services.hotformingstressknowhow.card1.problem": "Wysoki stosunek wytrzymałości do modułu sprężystości tytanu (wytrzymałość na rozciąganie 950 MPa vs. moduł sprężystości 114 GPa) powoduje ekstremalne odkształcenie sprężyste podczas formowania na zimno, gdzie materiał odzyskuje elastycznie 15-30% kąta gięcia po zwolnieniu obciążenia formującego. W przypadku grubych blach (10-50 mm) to odkształcenie sprężyste jest silnie nieliniowe i zależne od geometrii, co sprawia, że konwencjonalne naddatki na sprężynowanie są niedokładne i prowadzą do kosztownych poprawek wymiarowych.",
    "services.hotformingstressknowhow.card1.solution": "Zlokalizowane nagrzewanie podczerwienią (600-800°C) oraz modelowanie sprężynowania metodą elementów skończonych",
    "services.hotformingstressknowhow.card1.detail0": "Zlokalizowane matryce grzewcze na podczerwień działają wyłącznie na strefę gięcia, podnosząc temperaturę tytanu do 600-800°C, czyli optymalnego zakresu formowania na gorąco, w którym plastyczność wzrasta o 300%, a granica plastyczności spada o 60%, co znacząco redukuje wielkość odbicia sprężystego i umożliwia wykonywanie gięć o małym promieniu bez pękania.",
    "services.hotformingstressknowhow.card1.detail1": "Modele predykcyjne odbicia sprężystego w analizie metodą elementów skończonych (MES) symulują pełny cykl formowania: profil nagrzewania, formowanie pełzające w okresie wygrzewania, odzysk sprężysty podczas chłodzenia oraz geometrię końcową – generując skompensowane geometrie narzędzi, które przeciwdziałają przewidywanemu odchyleniu jeszcze przed uformowaniem pierwszej części.",
    "services.hotformingstressknowhow.card1.detail2": "Iteracyjna kompensacja przegięcia: przewidywany przez model MES kąt sprężynowania jest przekazywany do sterownika prasy krawędziowej jako automatyczne nastawienie przegięcia (zazwyczaj 3-12 stopni, w zależności od grubości blachy, promienia gięcia i temperatury), co skraca cykl prób i błędów z 3-5 iteracji do jednego zweryfikowanego ustawienia.",
    "services.hotformingstressknowhow.card1.detail3": "Wynik: dokładność kątowa na poziomie ±0,5 stopnia dla ciężkich płyt tytanowych formowanych na gorąco – eliminacja wtórnych operacji prostowania oraz zapewnienie zgodności pasowania z łączonymi elementami konstrukcyjnymi.",
    "services.hotformingstressknowhow.card2.title": "Pełnoskalowe cykle obróbki cieplnej odprężającej w próżni",
    "services.hotformingstressknowhow.card2.problem": "Walcowanie, kucie i spawanie grubych płyt tytanowych wprowadza znaczne naprężenia własne wynikające z niejednorodnego odkształcenia plastycznego podczas formowania (naprężenia walcowania sięgające 60% granicy plastyczności), naprężenia skurczu cieplnego w wielościegowych spoinach oraz koncentrację naprężeń na przejściach promieniowych formowanych elementów. Jeśli nie zostaną usunięte, te zablokowane naprężenia powodują opóźnione odkształcenia podczas obróbki skrawaniem, zmiany wymiarów w czasie oraz nieprzewidywalną pracę pod obciążeniem hiperbarycznym w głębinach lub cyklicznym zmęczeniowym.",
    "services.hotformingstressknowhow.card2.solution": "Wielofunkcyjny, skomputeryzowany piec do wyżarzania próżniowego – eliminacja naprężeń na poziomie 95% i więcej",
    "services.hotformingstressknowhow.card2.detail0": "Piec próżniowy do wyżarzania w pełnej skali z komorą roboczą o wymiarach umożliwiających obróbkę elementów do 12 000 x 4 500 x 4 000 mm. Cała konstrukcja spawana jest odprężana w jednym cyklu termicznym, eliminując konieczność lokalnego lub segmentowego odprężania.",
    "services.hotformingstressknowhow.card2.detail1": "Komputerowe sterowanie cyklem termicznym z równomiernością ±5°C w całym wsadzie: nagrzew do 540-650°C z szybkością 50°C/godz., wygrzewanie przez 1 godzinę na każde 25 mm grubości, chłodzenie z szybkością 50°C/godz. do 300°C, następnie naturalna konwekcja do temperatury pokojowej – zapewniając całkowitą relaksację naprężeń bez odkształceń wywołanych gradientem termicznym.",
    "services.hotformingstressknowhow.card2.detail2": "Próżnia utrzymywana na poziomie ≤10⁻⁵ mbar przez cały cykl termiczny – zapobiega utlenianiu powierzchni, tworzeniu się warstwy alfa-case oraz odbarwieniom na elementach tytanowych, eliminując konieczność późniejszego czyszczenia chemicznego lub mechanicznego usuwania zgorzeliny.",
    "services.hotformingstressknowhow.card2.detail3": "Wynik: wyeliminowano ponad 95% naprężeń szczątkowych po spawaniu i formowaniu – potwierdzone metodą przecięcia i pomiarów tensometrycznych zgodnie z ASTM E837. Konstrukcje zachowują stabilność wymiarową podczas późniejszej obróbki skrawaniem, transportu, montażu oraz cykli termicznych w warunkach głębinowych hiperbarycznych lub kriogenicznych.",
    "services.hotformingstressknowhow.relief_knowhow": "Wiedza w zakresie odprężania"
  }
};

const langs = ['de', 'fr', 'es', 'pt', 'it', 'ko', 'nl', 'pl'];
const en = JSON.parse(fs.readFileSync('src/i18n/translations/en.json', 'utf8'));

langs.forEach(lang => {
  const filePath = `src/i18n/translations/${lang}.json`;
  const data = JSON.parse(fs.readFileSync(filePath, 'utf8'));
  const trans = translations[lang];
  let updated = 0;
  
  Object.keys(trans).forEach(key => {
    if (data[key] === undefined || data[key] === en[key]) {
      data[key] = trans[key];
      updated++;
    }
  });
  
  fs.writeFileSync(filePath, JSON.stringify(data, null, 2) + '\n', 'utf8');
  console.log(`${lang}: ${updated} keys updated`);
});

console.log('\n所有8种语言的 HotFormingStressKnowHow 翻译已写入完成！');