import fs from 'fs';

const translations = {
  // ===== Japanese (JA) =====
  ja: {
    "services.extrusionprocessspectrum.section_badge": "押出加工能力",
    "services.extrusionprocessspectrum.title_part1": "チタン押出加工",
    "services.extrusionprocessspectrum.subtitle": "複雑な構造用プロファイルからシームレスな厚肉管、精密中空マルチチャンネル形状まで — ミッションクリティカルなチタン部品のための3つの専門押出加工ワークフロー。",
    "services.extrusionprocessspectrum.0.title": "複雑形状構造用押出プロファイル",
    "services.extrusionprocessspectrum.0.subtitle": "ニアネット連続T、L、U & H形断面",
    "services.extrusionprocessspectrum.0.desc": "T、L、U、H形構造断面のニアネット連続押出加工を実行 — 溶接継手や機械的ファスナーなしでシームレスな耐荷重機体、輸送用レール、産業用ガイドスライドを実現。",
    "services.extrusionprocessspectrum.0.cap0": "複雑な非対称構造プロファイルのニアネット押出成形",
    "services.extrusionprocessspectrum.0.cap1": "同時マルチプロファイル生産のためのマルチキャビティ金型設計",
    "services.extrusionprocessspectrum.0.cap2": "全長12,000mmにわたる一貫した肉厚",
    "services.extrusionprocessspectrum.0.cap3": "寸法安定性のための押出後ストレッチ矯正",
    "services.extrusionprocessspectrum.1.title": "シームレス厚肉管",
    "services.extrusionprocessspectrum.1.subtitle": "高圧モノリシック海底配管ハウジング",
    "services.extrusionprocessspectrum.1.desc": "溶接管製造に内在する熱影響部の微小亀裂脆弱性を回避 — 縦方向溶接線のない高圧モノリシック海底配管ハウジングを成形。",
    "services.extrusionprocessspectrum.1.cap0": "肉厚4.0mm〜50mm以上のシームレス管押出",
    "services.extrusionprocessspectrum.1.cap1": "マンドレルガイドによる内径制御 ±0.5mm",
    "services.extrusionprocessspectrum.1.cap2": "5,000 PSI以上の耐水圧試験合格",
    "services.extrusionprocessspectrum.1.cap3": "縦溶接継ぎ目なし — 熱影響部ゼロ、溶接検査不要",
    "services.extrusionprocessspectrum.2.title": "精密中空マルチチャンネル形状",
    "services.extrusionprocessspectrum.2.subtitle": "冷却用空隙のためのカスタムマンドレル構成",
    "services.extrusionprocessspectrum.2.desc": "単一のチタン押出ブランク内部に複数の冷却用空隙や軽量化キャビティを融合するカスタム内部マンドレル構成 — 圧延や成形では不可能。",
    "services.extrusionprocessspectrum.2.cap0": "2〜8個の内部チャンネルを持つマルチボイド中空形状",
    "services.extrusionprocessspectrum.2.cap1": "非対称およびオフセットキャビティパターンのカスタムマンドレル設計",
    "services.extrusionprocessspectrum.2.cap2": "隣接キャビティ間の一貫した壁分割",
    "services.extrusionprocessspectrum.2.cap3": "熱交換器セクションや軽量構造用梁に最適",
    "services.extrusionspecsdashboard.section_badge": "押出加工仕様",
    "services.extrusionspecsdashboard.title_part1": "押出加工",
    "services.extrusionspecsdashboard.subtitle": "油圧プレス能力、直線配送長さ、断面包絡線、およびチタン押出設備の肉厚限界。",
    "services.extrusionspecsdashboard.card0.label": "押出プレスの力",
    "services.extrusionspecsdashboard.card0.desc": "最大6,000メトリックトンにまで拡張可能な高トン数連続シリンダー能力 — 高温で複雑な金型形状を通してチタンビレットを押し出すのに必要な圧縮力を提供。",
    "services.extrusionspecsdashboard.card1.label": "最大直線プロファイル長さ",
    "services.extrusionspecsdashboard.card1.desc": "最大12メートルの単一片無中断合金構造を押出 — 突合せ溶接や機械的接合なしで全長構造プロファイルに対応。",
    "services.extrusionspecsdashboard.card2.label": "断面外接円",
    "services.extrusionspecsdashboard.card2.desc": "最大350 mmの外接円直径の複雑な幾何学的包絡線に対応 — 大型構造プロファイル、厚肉管、マルチチャンネル中空形状に対応。",
    "services.extrusionspecsdashboard.card3.label": "構造用肉厚一貫性",
    "services.extrusionspecsdashboard.card3.desc": "4.0 mmから50 mm以上の厚肉プロファイルまでのバランスの取れた厚肉断面限界に対応 — 薄肉軽量セクションから重構造用耐荷重部材まで対応。",
    "services.extrusionspecsdashboard.footnote": "すべての押出加工は高温（900〜1050°C）でガラス潤滑剤エンベロープを使用して実施。押出後のストレッチ矯正と超音波検査が全プロファイルで利用可能。",
    "services.extrusionlubricationknowhow.section_badge": "プロセスエンジニアリング",
    "services.extrusionlubricationknowhow.title_part1": "金型潤滑 &",
    "services.extrusionlubricationknowhow.subtitle_highlight": "熱制御ノウハウ",
    "services.extrusionlubricationknowhow.subtitle": "チタンの高温での固着、金型摩耗、直線歪みを克服するには、特殊なガラス潤滑と等温ツーリング制御が必要です。航空宇宙グレードの押出表面と真直度を実現する方法をご紹介します。",
    "services.extrusionlubricationknowhow.challenge": "課題",
    "services.extrusionlubricationknowhow.solution": "当社のソリューション",
    "services.extrusionlubricationknowhow.card1.title": "高度な溶融ガラスエンベロープ潤滑",
    "services.extrusionlubricationknowhow.card1.problem": "900〜1050°Cでのチタンの熱間押出中、極度の圧力（6,000メトリックトン）と温度により、チタンビレットと金型鋼表面の間に深刻な付着が発生 — 押出プロファイルの表面に表面破れ、焼付き、特徴的なフィッシュボーン波模様が発生し、航空宇宙や構造用途に不適となり、広範な押出後研削やスクラップが必要となる。",
    "services.extrusionlubricationknowhow.card1.solution": "航空宇宙認定のマイクロガラス粉末マトリックスによる液体境界層形成",
    "services.extrusionlubricationknowhow.card1.detail0": "航空宇宙認定のマイクロガラス粉末（粒径50〜200 µm）を押出プレスに挿入前に予熱したチタンビレットに均一コーティングとして塗布 — ガラス組成は押出温度（950〜1050°C）で溶融するよう精密に調整され、ビレットと金型ベアリング面の間に連続的な粘性液体境界を形成",
    "services.extrusionlubricationknowhow.card1.detail1": "溶融ガラス層（押出温度での粘度10³〜10⁵ポアズ）が10〜30 µm厚の流体力学的潤滑膜を形成 — チタンを金型鋼から完全に隔離し、表面破れ、焼付き、フィッシュボーン波形成の原因となる金属間接触を排除",
    "services.extrusionlubricationknowhow.card1.detail2": "押出ストローク全体を通して連続潤滑：ガラスコーティングはダミーブロックのリザーバーから補充され、新しいビレット材料が金型に供給される際にも液体境界層を維持 — 最初から最後まで均一な表面品質を保証",
    "services.extrusionlubricationknowhow.card1.detail3": "結果：押出プレスから直接Ra 1.6〜3.2 µmの表面仕上げ — 表面破れなし、焼付きなし、フィッシュボーン波なし — 二次的表面処理の必要性を排除し、材料歩留まりを最大化",
    "services.extrusionlubricationknowhow.card2.title": "等温ツーリングサイクル＆ストレッチ矯正",
    "services.extrusionlubricationknowhow.card2.problem": "チタンの高い押出温度（900〜1050°C）と低い熱伝導率により、押出中に金型面全体に大きな熱勾配が発生 — プロファイル断面全体で材料流速差が生じ、軸方向のねじれ、長手方向の反り、断面歪みを引き起こす。積極的な熱管理と押出後補正がなければ、これらの幾何学的欠陥により長尺押出プロファイルは構造組立に不適となる。",
    "services.extrusionlubricationknowhow.card2.solution": "等温流動のための誘導金型加熱ループ＆マルチトンストレッチ矯正",
    "services.extrusionlubricationknowhow.card2.detail0": "金型ホルダーに埋め込まれた誘導加熱コイルが、押出サイクル全体を通して金型温度を目標設定値（通常950〜1000°C）に±5°Cの精度で維持 — 金型が押出から熱を奪うことで発生する進行性冷却を排除し、最初から最後まで均一な金属流動を保証",
    "services.extrusionlubricationknowhow.card2.detail1": "マルチゾーン誘導制御：金型中央、ベアリング面、周辺部の個別加熱ゾーンを独立して調整 — 中央部に対するプロファイル端部の高い熱損失を補償し、断面全体で均一な材料速度を確保して差動流動誘起ねじれを排除",
    "services.extrusionlubricationknowhow.card2.detail2": "マルチトン油圧テンションベッドでの押出後ストレッチ矯正：押出プロファイルを両端で把持し、制御された引張荷重（通常1〜3%の永久伸び）を加える — この塑性変形により軸方向のねじれ、長手方向の反り、断面歪みを除去し、真直度を±0.5 mm/m以内に改善",
    "services.extrusionlubricationknowhow.card2.detail3": "結果：真直度±0.5 mm/m以内、ねじれなし、寸法適合の押出プロファイルを納品 — 二次的な矯正や手直しなしで構造組立に直接統合可能",
    "services.extrusiondedicatedcta.section_badge": "24時間押出加工実現性レビュー",
    "services.extrusiondedicatedcta.title_part1": "Buy-to-Flyスクラップを削減しますか？",
    "services.extrusiondedicatedcta.subtitle": "断面図面、プロファイル仕様書、年間数量予測をアップロードしてください — 金型実現性分析、ガラス潤滑戦略、等温ツーリング設計、ストレッチ矯正計画、プロトタイプから本生産までのマルチティア価格設定を含む迅速な24時間製造レビューを提供します。",
    "services.extrusiondedicatedcta.nda": "NDA保護",
    "services.extrusiondedicatedcta.compliant": "ITAR / AS9100D準拠",
    "services.extrusiondedicatedcta.response": "24時間以内に回答"
  },
  // ===== German (DE) =====
  de: {
    "services.extrusionprocessspectrum.section_badge": "Strangpress-Kapazitäten",
    "services.extrusionprocessspectrum.title_part1": "Titan-Strangpressen",
    "services.extrusionprocessspectrum.subtitle": "Von komplexen Strukturprofilen über nahtlose dickwandige Rohre bis hin zu präzisen hohlen Mehrkanalformen — drei spezialisierte Strangpress-Workflows für missionkritische Titankomponenten.",
    "services.extrusionprocessspectrum.0.title": "Komplexe Profil-Strukturextrusion",
    "services.extrusionprocessspectrum.0.subtitle": "Nahe-endkonturnahe T-, L-, U- & H-Profile",
    "services.extrusionprocessspectrum.0.desc": "Ausführung nahe-endkonturnaher Strangpressprofile für T-, L-, U- und H-Strukturabschnitte — nahtlose lasttragende Flugzeugzellen, Transportschienen und industrielle Führungsschienen ohne Schweißverbindungen oder mechanische Befestigungselemente.",
    "services.extrusionprocessspectrum.0.cap0": "Nahe-endkonturnahe Strangpressung komplexer asymmetrischer Strukturprofile",
    "services.extrusionprocessspectrum.0.cap1": "Mehrkavitäten-Werkzeugauslegung für gleichzeitige Mehrprofilproduktion",
    "services.extrusionprocessspectrum.0.cap2": "Gleichbleibende Wanddicke über die gesamte extrudierte Länge von 12.000 mm",
    "services.extrusionprocessspectrum.0.cap3": "Nach dem Strangpressen erfolgendes Streckrichten für Dimensionsstabilität",
    "services.extrusionprocessspectrum.1.title": "Nahtlose dickwandige Rohre",
    "services.extrusionprocessspectrum.1.subtitle": "Hochdruck-Monolithische Unterwasser-Rohrgehäuse",
    "services.extrusionprocessspectrum.1.desc": "Formgebung hochdruck-monolithischer Unterwasser-Rohrgehäuse ohne Längsschweißnähte — Vermeidung der bei geschweißten Rohren inhärenten Heißrissanfälligkeit in der Wärmeeinflusszone.",
    "services.extrusionprocessspectrum.1.cap0": "Nahtlose Rohrstrangpressung mit Wanddicken von 4,0 mm bis 50+ mm",
    "services.extrusionprocessspectrum.1.cap1": "Dorngeführte Innendurchmesserkontrolle innerhalb ±0,5 mm",
    "services.extrusionprocessspectrum.1.cap2": "Hydrostatisch geprüft auf 5.000+ PSI Betriebsdruck",
    "services.extrusionprocessspectrum.1.cap3": "Keine Längsschweißnaht — keine Wärmeeinflusszone, keine Schweißprüfung erforderlich",
    "services.extrusionprocessspectrum.2.title": "Präzise hohle Mehrkanal-Formen",
    "services.extrusionprocessspectrum.2.subtitle": "Kundenspezifische Dornkonfigurationen für Kühlhohlräume",
    "services.extrusionprocessspectrum.2.desc": "Antrieb kundenspezifischer Innendornkonfigurationen zur Verschmelzung mehrerer Kühlhohlräume oder Gewichtseinsparungskavitäten innerhalb eines einzigen Titanstrangpressrohlings — mit Walz- oder Umformverfahren nicht herstellbar.",
    "services.extrusionprocessspectrum.2.cap0": "Mehrfachhohlraumformen mit 2-8 inneren Kanälen",
    "services.extrusionprocessspectrum.2.cap1": "Kundenspezifische Dornauslegungen für asymmetrische und versetzte Kavitätsmuster",
    "services.extrusionprocessspectrum.2.cap2": "Gleichmäßige Wandtrennung zwischen benachbarten Kavitäten",
    "services.extrusionprocessspectrum.2.cap3": "Ideal für Wärmetauscherabschnitte und leichte Strukturträger",
    "services.extrusionspecsdashboard.section_badge": "Strangpress-Spezifikationen",
    "services.extrusionspecsdashboard.title_part1": "Strangpressen",
    "services.extrusionspecsdashboard.subtitle": "Hydraulische Presskraft, maximale Profillänge, Querschnittshüllkurve und Wanddickengrenzen unserer Titanstrangpressanlage.",
    "services.extrusionspecsdashboard.card0.label": "Strangpresskraft",
    "services.extrusionspecsdashboard.card0.desc": "Hochtonnagige kontinuierliche Zylinderkapazität bis zu 6.000 metrischen Tonnen — die Druckkraft, die benötigt wird, um Titanblöcke bei erhöhten Temperaturen durch komplexe Werkzeuggeometrien zu drücken.",
    "services.extrusionspecsdashboard.card1.label": "Maximale Profillänge",
    "services.extrusionspecsdashboard.card1.desc": "Einteilige, durchgehende Legierungsstrukturen bis zu 12 Metern Länge — Aufnahme von vollständigen Strukturprofilen ohne Stumpfschweißen oder mechanisches Fügen.",
    "services.extrusionspecsdashboard.card2.label": "Querschnitts-Hüllkreisdurchmesser",
    "services.extrusionspecsdashboard.card2.desc": "Bewältigung komplexer geometrischer Hüllkurven bis zu 350 mm Hüllkreisdurchmesser — Aufnahme großer Strukturprofile, dickwandiger Rohre und mehrkanaliger Hohlformen.",
    "services.extrusionspecsdashboard.card3.label": "Strukturelle Wanddickenkonstanz",
    "services.extrusionspecsdashboard.card3.desc": "Handhabung eines Dickenbereichs von 4,0 mm bis zu schweren 50+ mm Profilen — von dünnwandigen Leichtbauprofilen bis zu schweren tragenden Strukturbauteilen.",
    "services.extrusionspecsdashboard.footnote": "Alle Strangpressvorgänge bei erhöhten Temperaturen (900-1050°C) mit Glas-Schmiermittelhüllen. Nach dem Strangpressen erfolgendes Streckrichten und Ultraschallprüfung für alle Profile verfügbar.",
    "services.extrusionlubricationknowhow.section_badge": "Verfahrenstechnik",
    "services.extrusionlubricationknowhow.title_part1": "Werkzeugschmierung &",
    "services.extrusionlubricationknowhow.subtitle_highlight": "Thermische Steuerung",
    "services.extrusionlubricationknowhow.subtitle": "Die Bewältigung des Hochtemperatur-Klebens von Titan, des Werkzeugverschleißes und der Längsverformung erfordert spezielle Glasschmierung und isothermische Werkzeugsteuerung. So erzielen wir stranggepresste Oberflächen und Geradheit in Luftfahrtqualität.",
    "services.extrusionlubricationknowhow.challenge": "Die Herausforderung",
    "services.extrusionlubricationknowhow.solution": "Unsere Lösung",
    "services.extrusionlubricationknowhow.card1.title": "Fortschrittliche Schmelzglas-Hüllschmierung",
    "services.extrusionlubricationknowhow.card1.problem": "Beim Warmstrangpressen von Titan bei 900-1050°C verursachen der extreme Druck (6.000 Tonnen) und die Temperatur eine starke Adhäsion zwischen dem Titanblock und der Werkzeugstahloberfläche — was Oberflächenrisse, Kaltaufschweißungen und charakteristische 'Fischgräten'-Wellenmuster auf dem Strangpressprofil erzeugt, die die Oberfläche für Luft- und Raumfahrt- oder Strukturanwendungen unbrauchbar machen und umfangreiches Nachschleifen oder Verschrotten erfordern.",
    "services.extrusionlubricationknowhow.card1.solution": "Luftfahrtzertifizierte Mikroglaspulver-Matrizen bilden flüssige Grenzschichten",
    "services.extrusionlubricationknowhow.card1.detail0": "Luftfahrtzertifiziertes Mikroglaspulver (Partikelgröße 50-200 µm) wird als gleichmäßige Beschichtung auf den vorgewärmten Titanblock aufgetragen, bevor er in die Strangpresse eingeführt wird — die Glaszusammensetzung ist präzise formuliert, um bei Strangpresstemperatur (950-1050°C) zu schmelzen und eine kontinuierliche viskose Flüssigkeitsgrenze zwischen dem Block und der Werkzeuglagerfläche zu bilden",
    "services.extrusionlubricationknowhow.card1.detail1": "Die geschmolzene Glasschicht (Viskosität 10³-10⁵ Poise bei Strangpresstemperatur) erzeugt einen hydrodynamischen Schmierfilm von 10-30 µm Dicke — der Titan vollständig vom Werkzeugstahl isoliert und den Metall-zu-Metall-Kontakt eliminiert, der Oberflächenrisse, Kaltaufschweißungen und Fischgrätenwellenbildung verursacht",
    "services.extrusionlubricationknowhow.card1.detail2": "Kontinuierliche Schmierung während des gesamten Strangpresshubs: Die Glasbeschichtung wird aus einem Reservoir im Dummy-Block nachgefüllt, wodurch die flüssige Grenzschicht aufrechterhalten wird, während neues Blockmaterial in das Werkzeug einfließt — gleichbleibende Oberflächenqualität vom ersten bis zum letzten Meter",
    "services.extrusionlubricationknowhow.card1.detail3": "Ergebnis: Oberflächenrauheit Ra 1,6-3,2 µm direkt aus der Strangpresse — keine Oberflächenrisse, kein Kaltaufschweißen, keine Fischgrätenwellen — keine sekundäre Oberflächenbehandlung erforderlich, maximale Materialausbeute",
    "services.extrusionlubricationknowhow.card2.title": "Isothermische Werkzeugzyklen & Streckrichten",
    "services.extrusionlubricationknowhow.card2.problem": "Die hohe Strangpresstemperatur von Titan (900-1050°C) und die geringe Wärmeleitfähigkeit erzeugen während des Strangpressens erhebliche thermische Gradienten über die Werkzeugfläche — was zu unterschiedlichen Materialflussraten über den Profilquerschnitt führt, die axiale Verdrehung, Längskrümmung und Querschnittsverzerrung zur Folge haben. Ohne aktive Temperaturregelung und Nachbearbeitung machen diese geometrischen Fehler lange Strangpressprofile für die strukturelle Montage ungeeignet.",
    "services.extrusionlubricationknowhow.card2.solution": "Induktive Werkzeugheizschleifen für isothermen Fluss & Mehrtonnen-Streckrichten",
    "services.extrusionlubricationknowhow.card2.detail0": "In den Werkzeughalter eingebettete Induktionsheizspulen halten die Werkzeugtemperatur während des gesamten Strangpresszyklus auf dem Zielwert (typischerweise 950-1000°C) mit einer Genauigkeit von ±5°C — wodurch die fortschreitende Abkühlung vermieden wird, die sonst durch die Wärmeableitung vom Werkzeug auftreten würde, und ein gleichmäßiger Metallfluss von Anfang bis Ende gewährleistet wird",
    "services.extrusionlubricationknowhow.card2.detail1": "Mehrzonen-Induktionssteuerung: Einzelne Heizzonen an der Werkzeugmitte, der Lagerfläche und der Peripherie werden unabhängig geregelt — Ausgleich des höheren Wärmeverlusts an den Profilkanten gegenüber der Mitte, Gewährleistung einer gleichmäßigen Materialgeschwindigkeit über den gesamten Querschnitt und Beseitigung von durch unterschiedlichen Fluss induzierten Verdrehungen",
    "services.extrusionlubricationknowhow.card2.detail2": "Nach dem Strangpressen erfolgendes Streckrichten auf einer hydraulischen Mehrtonnen-Zugbank: Das stranggepresste Profil wird an beiden Enden gegriffen und einer kontrollierten Zugbelastung (typischerweise 1-3% bleibende Dehnung) ausgesetzt — diese plastische Verformung beseitigt axiale Verdrehung, Längskrümmung und Querschnittsverzerrung und verbessert die Geradheit auf ±0,5 mm/m",
    "services.extrusionlubricationknowhow.card2.detail3": "Ergebnis: Stranggepresste Profile mit Geradheit innerhalb ±0,5 mm/m, verdrehungsfrei und maßhaltig — bereit zur direkten Integration in Strukturbaugruppen ohne sekundäres Richten oder Nacharbeit",
    "services.extrusiondedicatedcta.section_badge": "24-Stunden-Strangpress-Machbarkeitsprüfung",
    "services.extrusiondedicatedcta.title_part1": "Buy-to-Fly-Abfall reduzieren?",
    "services.extrusiondedicatedcta.subtitle": "Laden Sie Ihre Querschnittszeichnungen, Profilspezifikationen und Jahresmengenprognosen für eine schnelle 24-Stunden-Fertigungsprüfung hoch — einschließlich Werkzeugmachbarkeitsanalyse, Glasschmierungsstrategie, isothermischer Werkzeugauslegung, Streckrichtplan und mehrstufiger Preisgestaltung vom Prototyp bis zur Serienproduktion.",
    "services.extrusiondedicatedcta.nda": "NDA-geschützt",
    "services.extrusiondedicatedcta.compliant": "ITAR / AS9100D-konform",
    "services.extrusiondedicatedcta.response": "Antwort innerhalb von 24 Stunden"
  },
  // ===== French (FR) =====
  fr: {
    "services.extrusionprocessspectrum.section_badge": "Capacités d'extrusion",
    "services.extrusionprocessspectrum.title_part1": "Extrusion de titane",
    "services.extrusionprocessspectrum.subtitle": "Des profils structurels complexes aux tubes à paroi épaisse sans soudure et aux formes creuses multi-canaux de précision — trois workflows d'extrusion spécialisés pour des composants en titane critiques.",
    "services.extrusionprocessspectrum.0.title": "Extrusion de profilés structurels complexes",
    "services.extrusionprocessspectrum.0.subtitle": "Sections T, L, U & H continues quasi nettes",
    "services.extrusionprocessspectrum.0.desc": "Exécution d'extrusion continue quasi nette pour les sections structurelles T, L, U et H — livraison de cellules d'avion porteuses sans soudure, de rails de transport et de glissières de guidage industrielles sans joints soudés ni fixations mécaniques.",
    "services.extrusionprocessspectrum.0.cap0": "Extrusion quasi nette de profils structurels asymétriques complexes",
    "services.extrusionprocessspectrum.0.cap1": "Conceptions de filières multi-cavités pour la production simultanée de multiples profils",
    "services.extrusionprocessspectrum.0.cap2": "Épaisseur de paroi constante sur toute la longueur extrudée de 12 000 mm",
    "services.extrusionprocessspectrum.0.cap3": "Dressage par étirement post-extrusion pour la stabilité dimensionnelle",
    "services.extrusionprocessspectrum.1.title": "Tubes à paroi épaisse sans soudure",
    "services.extrusionprocessspectrum.1.subtitle": "Boîtiers de tuyauterie sous-marine monolithiques haute pression",
    "services.extrusionprocessspectrum.1.desc": "Formation de boîtiers de tuyauterie sous-marine monolithiques haute pression sans aucune ligne de soudure longitudinale — évitant les vulnérabilités de micro-fissuration de la ZAT inhérentes à la fabrication de tubes soudés.",
    "services.extrusionprocessspectrum.1.cap0": "Extrusion de tubes sans soudure avec épaisseur de paroi de 4,0 mm à 50+ mm",
    "services.extrusionprocessspectrum.1.cap1": "Contrôle du diamètre intérieur guidé par mandrin à ±0,5 mm",
    "services.extrusionprocessspectrum.1.cap2": "Testé en pression hydrostatique à 5 000+ PSI",
    "services.extrusionprocessspectrum.1.cap3": "Aucune soudure longitudinale — ZAT nulle, aucune inspection de soudure requise",
    "services.extrusionprocessspectrum.2.title": "Formes creuses multi-canaux de précision",
    "services.extrusionprocessspectrum.2.subtitle": "Configurations de mandrin personnalisées pour vides de refroidissement",
    "services.extrusionprocessspectrum.2.desc": "Configuration de mandrins intérieurs personnalisés pour fusionner de multiples vides de refroidissement ou cavités d'allègement à l'intérieur d'une seule ébauche d'extrusion en titane — impossible à produire par laminage ou formage.",
    "services.extrusionprocessspectrum.2.cap0": "Formes creuses multi-vides avec 2 à 8 canaux internes",
    "services.extrusionprocessspectrum.2.cap1": "Conceptions de mandrin personnalisées pour motifs de cavités asymétriques et décalés",
    "services.extrusionprocessspectrum.2.cap2": "Partitionnement de paroi constant entre cavités adjacentes",
    "services.extrusionprocessspectrum.2.cap3": "Idéal pour les sections d'échangeurs de chaleur et les poutres structurelles légères",
    "services.extrusionspecsdashboard.section_badge": "Spécifications d'extrusion",
    "services.extrusionspecsdashboard.title_part1": "Extrusion",
    "services.extrusionspecsdashboard.subtitle": "Tonage de presse hydraulique, longueur de profilé linéaire, enveloppe de section transversale et limites d'épaisseur de paroi de notre installation d'extrusion de titane.",
    "services.extrusionspecsdashboard.card0.label": "Force de presse d'extrusion",
    "services.extrusionspecsdashboard.card0.desc": "Capacité de vérin continu à haute tonnage allant jusqu'à 6 000 tonnes métriques — fournissant la force de compression nécessaire pour pousser les billettes de titane à travers des géométries de filière complexes à températures élevées.",
    "services.extrusionspecsdashboard.card1.label": "Longueur de profilé linéaire maximale",
    "services.extrusionspecsdashboard.card1.desc": "Structures en alliage monobloc continues jusqu'à 12 mètres de longueur — permettant des profilés structurels de pleine longueur sans soudure bout à bout ni assemblage mécanique.",
    "services.extrusionspecsdashboard.card2.label": "Cercle circonscrit de la section transversale",
    "services.extrusionspecsdashboard.card2.desc": "Prise en charge d'enveloppes géométriques complexes jusqu'à 350 mm de diamètre de cercle circonscrit — permettant de grands profilés structurels, des tubes à paroi épaisse et des formes creuses multi-canaux.",
    "services.extrusionspecsdashboard.card3.label": "Régularité de l'épaisseur de paroi structurelle",
    "services.extrusionspecsdashboard.card3.desc": "Gestion des limites de sections épaisses de 4,0 mm jusqu'à des profilés lourds de 50+ mm — couvrant les sections légères à paroi mince jusqu'aux éléments porteurs structurels lourds.",
    "services.extrusionspecsdashboard.footnote": "Toute extrusion effectuée à températures élevées (900-1050°C) avec enveloppes de lubrifiant en verre. Dressage par étirement et inspection ultrasonique disponibles sur tous les profilés.",
    "services.extrusionlubricationknowhow.section_badge": "Ingénierie des procédés",
    "services.extrusionlubricationknowhow.title_part1": "Lubrification des filières &",
    "services.extrusionlubricationknowhow.subtitle_highlight": "Savoir-faire thermique",
    "services.extrusionlubricationknowhow.subtitle": "Vaincre le collage à haute température du titane, l'usure des filières et la distorsion linéaire nécessite une lubrification au verre spécialisée et un contrôle d'outillage isotherme. Voici comment nous obtenons des surfaces extrudées et une rectitude de qualité aérospatiale.",
    "services.extrusionlubricationknowhow.challenge": "Le défi",
    "services.extrusionlubricationknowhow.solution": "Notre solution",
    "services.extrusionlubricationknowhow.card1.title": "Lubrification avancée par enveloppe de verre fondu",
    "services.extrusionlubricationknowhow.card1.problem": "Lors de l'extrusion à chaud du titane à 900-1050°C, la pression extrême (6 000 tonnes métriques) et la température provoquent une adhésion sévère entre la billette de titane et la surface en acier de la filière — produisant des déchirures de surface, du grippage et des motifs d'ondes en « arête de poisson » caractéristiques sur le profilé extrudé, rendant la surface impropre aux applications aérospatiales ou structurelles et nécessitant un meulage post-extrusion ou une mise au rebut.",
    "services.extrusionlubricationknowhow.card1.solution": "Matrices de poudre de micro-verre certifiées aérospatiales formant des couches limites liquides",
    "services.extrusionlubricationknowhow.card1.detail0": "Poudre de micro-verre certifiée aérospatiale (taille de particules 50-200 µm) appliquée en revêtement uniforme sur la billette de titane préchauffée avant insertion dans la presse d'extrusion — la composition du verre est précisément formulée pour fondre à la température d'extrusion (950-1050°C), formant une frontière liquide visqueuse continue entre la billette et la surface d'appui de la filière",
    "services.extrusionlubricationknowhow.card1.detail1": "La couche de verre fondu (viscosité 10³-10⁵ Poise à la température d'extrusion) crée un film de lubrification hydrodynamique de 10-30 µm d'épaisseur — isolant complètement le titane de l'acier de la filière et éliminant le contact métal-métal à l'origine des déchirures de surface, du grippage et de la formation d'ondes en arête de poisson",
    "services.extrusionlubricationknowhow.card1.detail2": "Lubrification continue pendant toute la course d'extrusion : le revêtement de verre est reconstitué à partir d'un réservoir dans le bloc factice, maintenant la couche limite liquide à mesure que la nouvelle billette s'engage dans la filière — garantissant une qualité de surface uniforme du premier au dernier mètre",
    "services.extrusionlubricationknowhow.card1.detail3": "Résultat : finition de surface Ra 1,6-3,2 µm directement à la sortie de la presse — pas de déchirure de surface, pas de grippage, pas d'ondes en arête de poisson — éliminant le besoin de conditionnement de surface secondaire et maximisant le rendement matière",
    "services.extrusionlubricationknowhow.card2.title": "Cycles d'outillage isothermes & dressage par étirement",
    "services.extrusionlubricationknowhow.card2.problem": "La température d'extrusion élevée du titane (900-1050°C) et sa faible conductivité thermique créent des gradients thermiques significatifs à travers la face de la filière pendant l'extrusion — provoquant des vitesses d'écoulement différentielles du matériau à travers la section du profilé, entraînant une torsion axiale, un cintrage longitudinal et une distorsion de la section transversale. Sans gestion thermique active et correction post-extrusion, ces défauts géométriques rendent les profilés extrudés de grande longueur impropres à l'assemblage structurel.",
    "services.extrusionlubricationknowhow.card2.solution": "Boucles de chauffage inductif de filière pour écoulement isotherme & dressage par étirement multi-tonnes",
    "services.extrusionlubricationknowhow.card2.detail0": "Des bobines de chauffage par induction intégrées dans le porte-filière maintiennent la température de la filière au point de consigne cible (généralement 950-1000°C) avec une précision de ±5°C pendant tout le cycle d'extrusion — éliminant le refroidissement progressif qui se produirait autrement lorsque la filière conduit la chaleur loin de l'extrusion, assurant un écoulement uniforme du métal du début à la fin",
    "services.extrusionlubricationknowhow.card2.detail1": "Contrôle inductif multi-zones : les zones de chauffage individuelles au centre de la filière, à la surface d'appui et à la périphérie sont régulées indépendamment — compensant la perte de chaleur plus élevée aux bords du profilé par rapport au centre, assurant une vitesse de matériau uniforme sur toute la section transversale et éliminant la torsion induite par l'écoulement différentiel",
    "services.extrusionlubricationknowhow.card2.detail2": "Dressage par étirement post-extrusion sur un banc de tension hydraulique multi-tonnes : le profilé extrudé est saisi aux deux extrémités et soumis à une charge de traction contrôlée (généralement 1-3% d'allongement permanent) — cette déformation plastique élimine la torsion axiale, le cintrage longitudinal et la distorsion de la section transversale tout en améliorant la rectitude à ±0,5 mm/m",
    "services.extrusionlubricationknowhow.card2.detail3": "Résultat : profilés extrudés livrés avec une rectitude de ±0,5 mm/m, sans torsion et conformes dimensionnellement — prêts pour une intégration directe dans les assemblages structurels sans dressage secondaire ni reprise",
    "services.extrusiondedicatedcta.section_badge": "Examen de faisabilité d'extrusion en 24 heures",
    "services.extrusiondedicatedcta.title_part1": "Besoin de réduire les rebuts Buy-to-Fly ?",
    "services.extrusiondedicatedcta.subtitle": "Téléchargez vos dessins de section transversale, spécifications de profil et projections de volume annuel pour un examen rapide de fabrication en 24 heures — incluant analyse de faisabilité de filière, stratégie de lubrification au verre, conception d'outillage isotherme, plan de dressage par étirement et tarification multi-niveaux des prototypes aux volumes de production complets.",
    "services.extrusiondedicatedcta.nda": "Protégé par NDA",
    "services.extrusiondedicatedcta.compliant": "Conforme ITAR / AS9100D",
    "services.extrusiondedicatedcta.response": "Réponse sous 24 heures"
  },
  // ===== Spanish (ES) =====
  es: {
    "services.extrusionprocessspectrum.section_badge": "Capacidades de extrusión",
    "services.extrusionprocessspectrum.title_part1": "Extrusión de titanio",
    "services.extrusionprocessspectrum.subtitle": "Desde perfiles estructurales complejos hasta tubos sin costura de pared gruesa y formas huecas multicanal de precisión — tres flujos de trabajo de extrusión especializados para componentes de titanio de misión crítica.",
    "services.extrusionprocessspectrum.0.title": "Extrusión de perfiles estructurales complejos",
    "services.extrusionprocessspectrum.0.subtitle": "Secciones T, L, U y H continuas de casi red",
    "services.extrusionprocessspectrum.0.desc": "Ejecución de extrusión continua de casi red para secciones estructurales T, L, U y H — proporcionando fuselajes sin costura, rieles de tránsito y deslizaderas guía industriales sin uniones soldadas ni sujetadores mecánicos.",
    "services.extrusionprocessspectrum.0.cap0": "Extrusión de casi red de perfiles estructurales asimétricos complejos",
    "services.extrusionprocessspectrum.0.cap1": "Diseños de matriz multicavidad para producción simultánea de múltiples perfiles",
    "services.extrusionprocessspectrum.0.cap2": "Grosor de pared constante en toda la longitud extruida de 12,000 mm",
    "services.extrusionprocessspectrum.0.cap3": "Estirado y enderezado post-extrusión para estabilidad dimensional",
    "services.extrusionprocessspectrum.1.title": "Tubos sin costura de pared gruesa",
    "services.extrusionprocessspectrum.1.subtitle": "Carcasas de tubería submarina monolíticas de alta presión",
    "services.extrusionprocessspectrum.1.desc": "Formación de carcasas de tubería submarina monolíticas de alta presión sin líneas de soldadura longitudinales — evitando las vulnerabilidades de microfisuración en ZAT inherentes a la fabricación de tubos soldados.",
    "services.extrusionprocessspectrum.1.cap0": "Extrusión de tubos sin costura con espesor de pared de 4.0 mm a 50+ mm",
    "services.extrusionprocessspectrum.1.cap1": "Control del diámetro interior guiado por mandril dentro de ±0.5 mm",
    "services.extrusionprocessspectrum.1.cap2": "Probado hidrostáticamente a 5,000+ PSI de presión operativa",
    "services.extrusionprocessspectrum.1.cap3": "Sin costura de soldadura longitudinal — ZAT cero, sin inspección de soldadura requerida",
    "services.extrusionprocessspectrum.2.title": "Formas huecas multicanal de precisión",
    "services.extrusionprocessspectrum.2.subtitle": "Configuraciones de mandril personalizadas para cavidades de refrigeración",
    "services.extrusionprocessspectrum.2.desc": "Configuraciones de mandril interior personalizadas para fusionar múltiples cavidades de refrigeración o aligeramiento dentro de un único tocho de extrusión de titanio — imposible de producir con métodos de laminado o conformado.",
    "services.extrusionprocessspectrum.2.cap0": "Formas huecas multivacío con 2-8 canales internos",
    "services.extrusionprocessspectrum.2.cap1": "Diseños de mandril personalizados para patrones de cavidades asimétricas y descentradas",
    "services.extrusionprocessspectrum.2.cap2": "División de pared consistente entre cavidades adyacentes",
    "services.extrusionprocessspectrum.2.cap3": "Ideal para secciones de intercambiadores de calor y vigas estructurales ligeras",
    "services.extrusionspecsdashboard.section_badge": "Especificaciones de extrusión",
    "services.extrusionspecsdashboard.title_part1": "Extrusión",
    "services.extrusionspecsdashboard.subtitle": "Capacidad de prensa hidráulica, longitud de perfil lineal, envolvente de sección transversal y límites de espesor de pared de nuestra instalación de extrusión de titanio.",
    "services.extrusionspecsdashboard.card0.label": "Fuerza de prensa de extrusión",
    "services.extrusionspecsdashboard.card0.desc": "Capacidad de cilindro continuo de alto tonelaje de hasta 6,000 toneladas métricas — proporcionando la fuerza de compresión necesaria para empujar tochos de titanio a través de geometrías de matriz complejas a temperaturas elevadas.",
    "services.extrusionspecsdashboard.card1.label": "Longitud máxima de perfil lineal",
    "services.extrusionspecsdashboard.card1.desc": "Estructuras de aleación monobloque continuas de hasta 12 metros de longitud — acomodando perfiles estructurales de longitud completa sin soldadura a tope ni unión mecánica.",
    "services.extrusionspecsdashboard.card2.label": "Círculo circunscrito de sección transversal",
    "services.extrusionspecsdashboard.card2.desc": "Manejo de envolventes geométricas complejas de hasta 350 mm de diámetro de círculo circunscrito — acomodando grandes perfiles estructurales, tubos de pared gruesa y formas huecas multicanal.",
    "services.extrusionspecsdashboard.card3.label": "Consistencia de pared estructural",
    "services.extrusionspecsdashboard.card3.desc": "Manejo de límites de sección gruesa desde 4.0 mm hasta perfiles pesados de 50+ mm — abarcando desde secciones ligeras de pared delgada hasta miembros estructurales pesados de carga.",
    "services.extrusionspecsdashboard.footnote": "Toda extrusión realizada a temperaturas elevadas (900-1050°C) con envolventes de lubricante de vidrio. Estirado y enderezado post-extrusión e inspección ultrasónica disponibles en todos los perfiles.",
    "services.extrusionlubricationknowhow.section_badge": "Ingeniería de Procesos",
    "services.extrusionlubricationknowhow.title_part1": "Lubricación de matriz &",
    "services.extrusionlubricationknowhow.subtitle_highlight": "Control Térmico",
    "services.extrusionlubricationknowhow.subtitle": "Superar la adherencia a alta temperatura del titanio, el desgaste de la matriz y la distorsión lineal requiere lubricación de vidrio especializada y control de utillaje isotérmico. Así logramos superficies extrudidas y rectitud de grado aeroespacial.",
    "services.extrusionlubricationknowhow.challenge": "El Desafío",
    "services.extrusionlubricationknowhow.solution": "Nuestra Solución",
    "services.extrusionlubricationknowhow.card1.title": "Lubricación avanzada por envolvente de vidrio fundido",
    "services.extrusionlubricationknowhow.card1.problem": "Durante la extrusión en caliente de titanio a 900-1050°C, la presión extrema (6,000 toneladas métricas) y la temperatura causan adhesión severa entre el tocho de titanio y la superficie del acero de la matriz — produciendo desgarros superficiales, gripado y patrones de onda característicos de 'espina de pescado' en el perfil extruido que hacen que la superficie no sea apta para aplicaciones aeroespaciales o estructurales y requieran un rectificado post-extrusión extenso o desechado.",
    "services.extrusionlubricationknowhow.card1.solution": "Matrices de Micropolvo de Vidrio Certificado Aeroespacial que Forman Capas Límite Líquidas",
    "services.extrusionlubricationknowhow.card1.detail0": "Polvo de microvidrio certificado aeroespacial (tamaño de partícula 50-200 µm) aplicado como recubrimiento uniforme al tocho de titanio precalentado antes de la inserción en la prensa de extrusión — la composición del vidrio está formulada precisamente para fundirse a la temperatura de extrusión (950-1050°C), formando un límite líquido viscoso continuo entre el tocho y la superficie de apoyo de la matriz",
    "services.extrusionlubricationknowhow.card1.detail1": "La capa de vidrio fundido (viscosidad 10³-10⁵ Poise a temperatura de extrusión) crea una película de lubricación hidrodinámica de 10-30 µm de espesor — aislando completamente el titanio del acero de la matriz y eliminando el contacto metal-metal que causa desgarros superficiales, gripado y formación de ondas de espina de pescado",
    "services.extrusionlubricationknowhow.card1.detail2": "Lubricación continua durante toda la carrera de extrusión: el recubrimiento de vidrio se repone desde un depósito en el bloque ficticio, manteniendo la capa límite líquida a medida que el material fresco del tocho se alimenta a la matriz — garantizando una calidad superficial uniforme desde el primer metro hasta el último",
    "services.extrusionlubricationknowhow.card1.detail3": "Resultado: acabado superficial Ra 1.6-3.2 µm directamente de la prensa de extrusión — sin desgarros superficiales, sin gripado, sin ondas de espina de pescado — eliminando la necesidad de acondicionamiento superficial secundario y maximizando el rendimiento del material",
    "services.extrusionlubricationknowhow.card2.title": "Ciclos de utillaje isotérmico & estirado y enderezado",
    "services.extrusionlubricationknowhow.card2.problem": "La alta temperatura de extrusión del titanio (900-1050°C) y su baja conductividad térmica crean gradientes térmicos significativos a través de la cara de la matriz durante la extrusión — causando velocidades de flujo de material diferenciales a través de la sección transversal del perfil que resultan en torsión axial, combado longitudinal y distorsión de la sección transversal. Sin gestión térmica activa y corrección post-extrusión, estos defectos geométricos hacen que los perfiles extruidos de gran longitud no sean adecuados para el montaje estructural.",
    "services.extrusionlubricationknowhow.card2.solution": "Bucles de calentamiento inductivo de matriz para flujo isotérmico & estirado y enderezado multitonelada",
    "services.extrusionlubricationknowhow.card2.detail0": "Bobinas de calentamiento por inducción incrustadas en el portamatriz mantienen la temperatura de la matriz en el punto de consigna objetivo (típicamente 950-1000°C) con una precisión de ±5°C durante todo el ciclo de extrusión — eliminando el enfriamiento progresivo que de otro modo ocurriría a medida que la matriz conduce el calor lejos de la extrusión, asegurando un flujo de metal uniforme de principio a fin",
    "services.extrusionlubricationknowhow.card2.detail1": "Control inductivo multizona: las zonas de calentamiento individuales en el centro de la matriz, la superficie de apoyo y la periferia se regulan independientemente — compensando la mayor pérdida de calor en los bordes del perfil frente al centro, asegurando una velocidad de material uniforme en toda la sección transversal y eliminando la torsión inducida por flujo diferencial",
    "services.extrusionlubricationknowhow.card2.detail2": "Estirado y enderezado post-extrusión en un banco de tensión hidráulico multitonelada: el perfil extruido se sujeta por ambos extremos y se somete a una carga de tracción controlada (típicamente 1-3% de elongación permanente) — esta deformación plástica elimina la torsión axial, el combado longitudinal y la distorsión de la sección transversal, mejorando la rectitud a ±0.5 mm/m",
    "services.extrusionlubricationknowhow.card2.detail3": "Resultado: perfiles extruidos entregados con rectitud dentro de ±0.5 mm/m, sin torsión y dimensionalmente conformes — listos para integración directa en ensamblajes estructurales sin enderezado secundario ni retrabajo",
    "services.extrusiondedicatedcta.section_badge": "Revisión de viabilidad de extrusión en 24 horas",
    "services.extrusiondedicatedcta.title_part1": "¿Necesita comprimir el desperdicio Buy-to-Fly?",
    "services.extrusiondedicatedcta.subtitle": "Cargue sus dibujos de sección transversal, especificaciones de perfil y proyecciones de volumen anual para una revisión rápida de fabricación en 24 horas — incluyendo análisis de viabilidad de matriz, estrategia de lubricación de vidrio, diseño de utillaje isotérmico, plan de estirado y enderezado y precios multinivel desde prototipos hasta volúmenes de producción completos.",
    "services.extrusiondedicatedcta.nda": "Protegido por NDA",
    "services.extrusiondedicatedcta.compliant": "Cumplimiento ITAR / AS9100D",
    "services.extrusiondedicatedcta.response": "Respuesta en 24 horas"
  },
  // ===== Portuguese (PT) =====
  pt: {
    "services.extrusionprocessspectrum.section_badge": "Capacidades de extrusão",
    "services.extrusionprocessspectrum.title_part1": "Extrusão de titânio",
    "services.extrusionprocessspectrum.subtitle": "De perfis estruturais complexos a tubos sem costura de parede espessa e formas ocas multicanal de precisão — três fluxos de trabalho de extrusão especializados para componentes de titânio de missão crítica.",
    "services.extrusionprocessspectrum.0.title": "Extrusão de perfis estruturais complexos",
    "services.extrusionprocessspectrum.0.subtitle": "Seções T, L, U e H contínuas de quase rede",
    "services.extrusionprocessspectrum.0.desc": "Execução de extrusão contínua de quase rede para seções estruturais T, L, U e H — fornecendo fuselagens de aeronaves sem costura, trilhos de trânsito e corrediças-guia industriais sem juntas soldadas ou fixadores mecânicos.",
    "services.extrusionprocessspectrum.0.cap0": "Extrusão de quase rede de perfis estruturais assimétricos complexos",
    "services.extrusionprocessspectrum.0.cap1": "Projetos de matriz multicavidade para produção simultânea de múltiplos perfis",
    "services.extrusionprocessspectrum.0.cap2": "Espessura de parede consistente em todo o comprimento extrudado de 12.000 mm",
    "services.extrusionprocessspectrum.0.cap3": "Estiramento e endireitamento pós-extrusão para estabilidade dimensional",
    "services.extrusionprocessspectrum.1.title": "Tubos sem costura de parede espessa",
    "services.extrusionprocessspectrum.1.subtitle": "Gabinetes de tubulação submarina monolítica de alta pressão",
    "services.extrusionprocessspectrum.1.desc": "Formação de gabinetes de tubulação submarina monolítica de alta pressão sem linhas de solda longitudinal — evitando vulnerabilidades de microfissuração na ZTA inerentes à fabricação de tubos soldados.",
    "services.extrusionprocessspectrum.1.cap0": "Extrusão de tubo sem costura com espessura de parede de 4,0 mm a 50+ mm",
    "services.extrusionprocessspectrum.1.cap1": "Controle de diâmetro interno guiado por mandril dentro de ±0,5 mm",
    "services.extrusionprocessspectrum.1.cap2": "Testado hidrostaticamente a 5.000+ PSI de pressão operacional",
    "services.extrusionprocessspectrum.1.cap3": "Sem solda longitudinal — ZTA zero, sem inspeção de solda necessária",
    "services.extrusionprocessspectrum.2.title": "Formas ocas multicanal de precisão",
    "services.extrusionprocessspectrum.2.subtitle": "Configurações de mandril personalizadas para vazios de resfriamento",
    "services.extrusionprocessspectrum.2.desc": "Configurações personalizadas de mandril interno para fundir múltiplos vazios de resfriamento ou cavidades de redução de peso dentro de um único tarugo de extrusão de titânio — impossível de produzir com métodos de laminação ou conformação.",
    "services.extrusionprocessspectrum.2.cap0": "Formas ocas multivazios com 2-8 canais internos",
    "services.extrusionprocessspectrum.2.cap1": "Projetos de mandril personalizados para padrões de cavidade assimétricos e deslocados",
    "services.extrusionprocessspectrum.2.cap2": "Divisão de parede consistente entre cavidades adjacentes",
    "services.extrusionprocessspectrum.2.cap3": "Ideal para seções de trocador de calor e vigas estruturais leves",
    "services.extrusionspecsdashboard.section_badge": "Especificações de extrusão",
    "services.extrusionspecsdashboard.title_part1": "Extrusão",
    "services.extrusionspecsdashboard.subtitle": "Tonelagem da prensa hidráulica, comprimento linear do perfil, envelope de seção transversal e limites de espessura de parede de nossa instalação de extrusão de titânio.",
    "services.extrusionspecsdashboard.card0.label": "Força da prensa de extrusão",
    "services.extrusionspecsdashboard.card0.desc": "Capacidade de cilindro contínuo de alta tonelagem de até 6.000 toneladas métricas — fornecendo a força compressiva necessária para empurrar tarugos de titânio através de geometrias de matriz complexas a temperaturas elevadas.",
    "services.extrusionspecsdashboard.card1.label": "Comprimento máximo do perfil linear",
    "services.extrusionspecsdashboard.card1.desc": "Estruturas de liga monobloco contínuas de até 12 metros de comprimento — acomodando perfis estruturais de comprimento total sem solda de topo ou união mecânica.",
    "services.extrusionspecsdashboard.card2.label": "Círculo circunscrito da seção transversal",
    "services.extrusionspecsdashboard.card2.desc": "Lidando com envelopes geométricos complexos de até 350 mm de diâmetro de círculo circunscrito — acomodando grandes perfis estruturais, tubos de parede espessa e formas ocas multicanal.",
    "services.extrusionspecsdashboard.card3.label": "Consistência de parede estrutural",
    "services.extrusionspecsdashboard.card3.desc": "Gerenciamento de limites de seção espessa de 4,0 mm até perfis pesados de 50+ mm — abrangendo seções leves de parede fina até membros estruturais pesados de suporte de carga.",
    "services.extrusionspecsdashboard.footnote": "Toda extrusão realizada a temperaturas elevadas (900-1050°C) com envelopes de lubrificante de vidro. Estiramento e endireitamento pós-extrusão e inspeção ultrassônica disponíveis em todos os perfis.",
    "services.extrusionlubricationknowhow.section_badge": "Engenharia de Processos",
    "services.extrusionlubricationknowhow.title_part1": "Lubrificação de matriz &",
    "services.extrusionlubricationknowhow.subtitle_highlight": "Controle Térmico",
    "services.extrusionlubricationknowhow.subtitle": "Conquistar a aderência em alta temperatura do titânio, o desgaste da matriz e a distorção linear requer lubrificação de vidro especializada e controle isotérmico do ferramental. Veja como alcançamos superfícies extrudadas e retilineidade de grau aeroespacial.",
    "services.extrusionlubricationknowhow.challenge": "O Desafio",
    "services.extrusionlubricationknowhow.solution": "Nossa Solução",
    "services.extrusionlubricationknowhow.card1.title": "Lubrificação Avançada por Envoltório de Vidro Fundido",
    "services.extrusionlubricationknowhow.card1.problem": "Durante a extrusão a quente de titânio a 900-1050°C, a pressão extrema (6.000 toneladas métricas) e a temperatura causam adesão severa entre o tarugo de titânio e a superfície do aço da matriz — produzindo rasgos superficiais, gralhamento e padrões característicos de ondas 'espinha de peixe' no perfil extrudado que tornam a superfície inadequada para aplicações aeroespaciais ou estruturais e exigem retificação pós-extrusão extensa ou sucateamento.",
    "services.extrusionlubricationknowhow.card1.solution": "Matrizes de Micropó de Vidro Certificado Aeroespacial Formando Camadas Limite Líquidas",
    "services.extrusionlubricationknowhow.card1.detail0": "Pó de microvidro certificado aeroespacial (tamanho de partícula 50-200 µm) aplicado como revestimento uniforme ao tarugo de titânio pré-aquecido antes da inserção na prensa de extrusão — a composição do vidro é precisamente formulada para derreter à temperatura de extrusão (950-1050°C), formando um limite líquido viscoso contínuo entre o tarugo e a superfície de apoio da matriz",
    "services.extrusionlubricationknowhow.card1.detail1": "A camada de vidro fundido (viscosidade 10³-10⁵ Poise à temperatura de extrusão) cria um filme de lubrificação hidrodinâmico de 10-30 µm de espessura — isolando completamente o titânio do aço da matriz e eliminando o contato metal-metal que causa rasgos superficiais, gralhamento e formação de ondas espinha de peixe",
    "services.extrusionlubricationknowhow.card1.detail2": "Lubrificação contínua durante todo o curso de extrusão: o revestimento de vidro é reabastecido a partir de um reservatório no bloco fictício, mantendo a camada limite líquida à medida que o material fresco do tarugo alimenta a matriz — garantindo qualidade de superfície uniforme do primeiro ao último metro",
    "services.extrusionlubricationknowhow.card1.detail3": "Resultado: acabamento superficial Ra 1,6-3,2 µm diretamente da prensa de extrusão — sem rasgos superficiais, sem gralhamento, sem ondas espinha de peixe — eliminando a necessidade de condicionamento superficial secundário e maximizando o rendimento do material",
    "services.extrusionlubricationknowhow.card2.title": "Ciclos de ferramental isotérmico & estiramento e endireitamento",
    "services.extrusionlubricationknowhow.card2.problem": "A alta temperatura de extrusão do titânio (900-1050°C) e a baixa condutividade térmica criam gradientes térmicos significativos através da face da matriz durante a extrusão — causando taxas de fluxo de material diferenciais através da seção transversal do perfil que resultam em torção axial, curvamento longitudinal e distorção da seção transversal. Sem gerenciamento térmico ativo e correção pós-extrusão, esses defeitos geométricos tornam os perfis extrudados de longo comprimento inadequados para montagem estrutural.",
    "services.extrusionlubricationknowhow.card2.solution": "Laços de aquecimento indutivo de matriz para fluxo isotérmico & estiramento e endireitamento multitonalada",
    "services.extrusionlubricationknowhow.card2.detail0": "Bobinas de aquecimento por indução embutidas no suporte da matriz mantêm a temperatura da matriz no ponto de ajuste alvo (tipicamente 950-1000°C) com precisão de ±5°C durante todo o ciclo de extrusão — eliminando o resfriamento progressivo que de outra forma ocorreria à medida que a matriz conduz o calor para longe da extrusão, garantindo fluxo de metal uniforme do início ao fim",
    "services.extrusionlubricationknowhow.card2.detail1": "Controle indutivo multizona: zonas de aquecimento individuais no centro da matriz, superfície de apoio e periferia são reguladas independentemente — compensando a maior perda de calor nas bordas do perfil versus o centro, garantindo velocidade de material uniforme em toda a seção transversal e eliminando a torção induzida por fluxo diferencial",
    "services.extrusionlubricationknowhow.card2.detail2": "Estiramento e endireitamento pós-extrusão em um banco de tensão hidráulico multitonalada: o perfil extrudado é preso em ambas as extremidades e submetido a uma carga de tração controlada (tipicamente 1-3% de alongamento permanente) — esta deformação plástica remove torção axial, curvamento longitudinal e distorção da seção transversal enquanto melhora a retilineidade para dentro de ±0,5 mm/m",
    "services.extrusionlubricationknowhow.card2.detail3": "Resultado: perfis extrudados entregues com retilineidade dentro de ±0,5 mm/m, sem torção e dimensionalmente conformes — prontos para integração direta em montagens estruturais sem endireitamento secundário ou retrabalho",
    "services.extrusiondedicatedcta.section_badge": "Revisão de Viabilidade de Extrusão em 24 Horas",
    "services.extrusiondedicatedcta.title_part1": "Precisa Comprimir Sucata Buy-to-Fly?",
    "services.extrusiondedicatedcta.subtitle": "Carregue seus desenhos de seção transversal, especificações de perfil e projeções de volume anual para uma revisão rápida de fabricação em 24 horas — incluindo análise de viabilidade de matriz, estratégia de lubrificação de vidro, projeto de ferramental isotérmico, plano de estiramento e endireitamento e preços multicamadas desde protótipos até volumes de produção completos.",
    "services.extrusiondedicatedcta.nda": "Protegido por NDA",
    "services.extrusiondedicatedcta.compliant": "Conforme ITAR / AS9100D",
    "services.extrusiondedicatedcta.response": "Resposta em 24 Horas"
  },
  // ===== Italian (IT) =====
  it: {
    "services.extrusionprocessspectrum.section_badge": "Capacità di estrusione",
    "services.extrusionprocessspectrum.title_part1": "Estrusione di titanio",
    "services.extrusionprocessspectrum.subtitle": "Dai profili strutturali complessi ai tubi senza saldatura a parete spessa e alle forme cave multicanale di precisione — tre flussi di lavoro di estrusione specializzati per componenti in titanio di importanza critica.",
    "services.extrusionprocessspectrum.0.title": "Estrusione di profili strutturali complessi",
    "services.extrusionprocessspectrum.0.subtitle": "Sezioni T, L, U e H continue a quasi rete",
    "services.extrusionprocessspectrum.0.desc": "Esecuzione di estrusione continua a quasi rete per sezioni strutturali T, L, U e H — consegna di cellule di aeromobili senza saldatura, rotaie di transito e guide scorrevoli industriali senza giunti saldati o elementi di fissaggio meccanici.",
    "services.extrusionprocessspectrum.0.cap0": "Estrusione a quasi rete di profili strutturali asimmetrici complessi",
    "services.extrusionprocessspectrum.0.cap1": "Progetti di matrici multicavità per produzione simultanea di profili multipli",
    "services.extrusionprocessspectrum.0.cap2": "Spessore di parete costante su tutta la lunghezza estrusa di 12.000 mm",
    "services.extrusionprocessspectrum.0.cap3": "Raddrizzatura per stiramento post-estrusione per stabilità dimensionale",
    "services.extrusionprocessspectrum.1.title": "Tubi senza saldatura a parete spessa",
    "services.extrusionprocessspectrum.1.subtitle": "Custodie per tubazioni sottomarine monolitiche ad alta pressione",
    "services.extrusionprocessspectrum.1.desc": "Formazione di custodie per tubazioni sottomarine monolitiche ad alta pressione senza linee di saldatura longitudinali — evitando le vulnerabilità di microcricche nella ZTA inerenti alla produzione di tubi saldati.",
    "services.extrusionprocessspectrum.1.cap0": "Estrusione di tubi senza saldatura con spessore di parete da 4,0 mm a 50+ mm",
    "services.extrusionprocessspectrum.1.cap1": "Controllo del diametro interno guidato da mandrino entro ±0,5 mm",
    "services.extrusionprocessspectrum.1.cap2": "Testato idrostaticamente a 5.000+ PSI di pressione operativa",
    "services.extrusionprocessspectrum.1.cap3": "Nessuna saldatura longitudinale — ZTA zero, nessuna ispezione di saldatura richiesta",
    "services.extrusionprocessspectrum.2.title": "Forme cave multicanale di precisione",
    "services.extrusionprocessspectrum.2.subtitle": "Configurazioni personalizzate del mandrino per cavità di raffreddamento",
    "services.extrusionprocessspectrum.2.desc": "Configurazioni personalizzate del mandrino interno per fondere multiple cavità di raffreddamento o alleggerimento all'interno di un singolo billetta di estrusione in titanio — impossibile da produrre con metodi di laminazione o formatura.",
    "services.extrusionprocessspectrum.2.cap0": "Forme cave multivuoto con 2-8 canali interni",
    "services.extrusionprocessspectrum.2.cap1": "Progetti di mandrino personalizzati per motivi di cavità asimmetrici e sfalsati",
    "services.extrusionprocessspectrum.2.cap2": "Partizione di parete costante tra cavità adiacenti",
    "services.extrusionprocessspectrum.2.cap3": "Ideale per sezioni di scambiatori di calore e travi strutturali leggere",
    "services.extrusionspecsdashboard.section_badge": "Specifiche di estrusione",
    "services.extrusionspecsdashboard.title_part1": "Estrusione",
    "services.extrusionspecsdashboard.subtitle": "Tonellaggio della pressa idraulica, lunghezza del profilo lineare, inviluppo della sezione trasversale e limiti di spessore di parete del nostro impianto di estrusione di titanio.",
    "services.extrusionspecsdashboard.card0.label": "Forza della pressa di estrusione",
    "services.extrusionspecsdashboard.card0.desc": "Capacità del cilindro continuo ad alta tonnellaggio fino a 6.000 tonnellate metriche — fornendo la forza di compressione necessaria per spingere le billette di titanio attraverso geometrie di matrici complesse a temperature elevate.",
    "services.extrusionspecsdashboard.card1.label": "Lunghezza massima del profilo lineare",
    "services.extrusionspecsdashboard.card1.desc": "Strutture in lega monoblocco continue fino a 12 metri di lunghezza — che ospitano profili strutturali a lunghezza intera senza saldatura di testa o unione meccanica.",
    "services.extrusionspecsdashboard.card2.label": "Cerchio circoscritto della sezione trasversale",
    "services.extrusionspecsdashboard.card2.desc": "Gestione di inviluppi geometrici complessi fino a 350 mm di diametro del cerchio circoscritto — che ospita grandi profili strutturali, tubi a parete spessa e forme cave multicanale.",
    "services.extrusionspecsdashboard.card3.label": "Consistenza della parete strutturale",
    "services.extrusionspecsdashboard.card3.desc": "Gestione dei limiti di sezione spessa da 4,0 mm fino a profili pesanti di 50+ mm — che spazia da sezioni leggere a parete sottile a membri strutturali pesanti portanti.",
    "services.extrusionspecsdashboard.footnote": "Tutta l'estrusione eseguita a temperature elevate (900-1050°C) con involucri di lubrificante in vetro. Raddrizzatura per stiramento post-estrusione e ispezione ultrasonica disponibili su tutti i profili.",
    "services.extrusionlubricationknowhow.section_badge": "Ingegneria di Processo",
    "services.extrusionlubricationknowhow.title_part1": "Lubrificazione dello stampo &",
    "services.extrusionlubricationknowhow.subtitle_highlight": "Controllo Termico",
    "services.extrusionlubricationknowhow.subtitle": "Conquistare l'adesione ad alta temperatura del titanio, l'usura dello stampo e la distorsione lineare richiede lubrificazione specializzata al vetro e controllo isotermico dell'attrezzatura. Ecco come otteniamo superfici estrudate e rettilineità di grado aerospaziale.",
    "services.extrusionlubricationknowhow.challenge": "La Sfida",
    "services.extrusionlubricationknowhow.solution": "La Nostra Soluzione",
    "services.extrusionlubricationknowhow.card1.title": "Lubrificazione Avanzata a Involucro di Vetro Fuso",
    "services.extrusionlubricationknowhow.card1.problem": "Durante l'estrusione a caldo del titanio a 900-1050°C, la pressione estrema (6.000 tonnellate metriche) e la temperatura causano una grave adesione tra la billetta di titanio e la superficie dell'acciaio dello stampo — producendo strappi superficiali, grippaggio e caratteristici motivi ondulati a 'lisca di pesce' sul profilo estruso che rendono la superficie inadatta per applicazioni aerospaziali o strutturali e richiedono un'ampia rettifica post-estrusione o la rottamazione.",
    "services.extrusionlubricationknowhow.card1.solution": "Matrici di Micropolvere di Vetro Certificate Aerospaziali che Formano Strati Limite Liquidi",
    "services.extrusionlubricationknowhow.card1.detail0": "Polvere di microvetro certificata aerospaziale (dimensione delle particelle 50-200 µm) applicata come rivestimento uniforme sulla billetta di titanio preriscaldata prima dell'inserimento nella pressa di estrusione — la composizione del vetro è formulata con precisione per fondersi alla temperatura di estrusione (950-1050°C), formando un confine liquido viscoso continuo tra la billetta e la superficie di appoggio dello stampo",
    "services.extrusionlubricationknowhow.card1.detail1": "Lo strato di vetro fuso (viscosità 10³-10⁵ Poise alla temperatura di estrusione) crea un film di lubrificazione idrodinamico spesso 10-30 µm — isolando completamente il titanio dall'acciaio dello stampo ed eliminando il contatto metallo-metallo che causa strappi superficiali, grippaggio e formazione di onde a lisca di pesce",
    "services.extrusionlubricationknowhow.card1.detail2": "Lubrificazione continua durante l'intera corsa di estrusione: il rivestimento di vetro viene reintegrato da un serbatoio nel blocco fittizio, mantenendo lo strato limite liquido mentre il materiale fresco della billetta alimenta lo stampo — garantendo una qualità superficiale uniforme dal primo all'ultimo metro",
    "services.extrusionlubricationknowhow.card1.detail3": "Risultato: finitura superficiale Ra 1,6-3,2 µm direttamente dalla pressa di estrusione — nessuno strappo superficiale, nessun grippaggio, nessuna onda a lisca di pesce — eliminando la necessità di condizionamento superficiale secondario e massimizzando la resa del materiale",
    "services.extrusionlubricationknowhow.card2.title": "Cicli di attrezzatura isotermica & raddrizzatura per stiramento",
    "services.extrusionlubricationknowhow.card2.problem": "L'elevata temperatura di estrusione del titanio (900-1050°C) e la bassa conduttività termica creano gradienti termici significativi attraverso la faccia dello stampo durante l'estrusione — causando velocità di flusso del materiale differenziali attraverso la sezione trasversale del profilo che risultano in torsione assiale, incurvamento longitudinale e distorsione della sezione trasversale. Senza una gestione termica attiva e una correzione post-estrusione, questi difetti geometrici rendono i profili estrusi di lunga lunghezza inadatti per l'assemblaggio strutturale.",
    "services.extrusionlubricationknowhow.card2.solution": "Circuiti di Riscaldamento Induttivo dello Stampo per Flusso Isotermico & Raddrizzatura per Stiramento Multi-Tonnellata",
    "services.extrusionlubricationknowhow.card2.detail0": "Bobine di riscaldamento a induzione incorporate nel portastampo mantengono la temperatura dello stampo al punto di impostazione target (tipicamente 950-1000°C) con una precisione di ±5°C durante l'intero ciclo di estrusione — eliminando il raffreddamento progressivo che altrimenti si verificherebbe mentre lo stampo conduce il calore lontano dall'estrusione, garantendo un flusso di metallo uniforme dall'inizio alla fine",
    "services.extrusionlubricationknowhow.card2.detail1": "Controllo induttivo multizona: le zone di riscaldamento individuali al centro dello stampo, sulla superficie di appoggio e alla periferia sono regolate indipendentemente — compensando la maggiore perdita di calore ai bordi del profilo rispetto al centro, garantendo una velocità del materiale uniforme su tutta la sezione trasversale ed eliminando la torsione indotta dal flusso differenziale",
    "services.extrusionlubricationknowhow.card2.detail2": "Raddrizzatura per stiramento post-estrusione su un banco di tensione idraulico multi-tonnellata: il profilo estruso viene afferrato ad entrambe le estremità e sottoposto a un carico di trazione controllato (tipicamente 1-3% di allungamento permanente) — questa deformazione plastica rimuove la torsione assiale, l'incurvamento longitudinale e la distorsione della sezione trasversale, migliorando la rettilineità entro ±0,5 mm/m",
    "services.extrusionlubricationknowhow.card2.detail3": "Risultato: profili estrusi consegnati con rettilineità entro ±0,5 mm/m, senza torsione e dimensionalmente conformi — pronti per l'integrazione diretta in assemblaggi strutturali senza raddrizzatura secondaria o rilavorazione",
    "services.extrusiondedicatedcta.section_badge": "Revisione di Fattibilità di Estrusione in 24 Ore",
    "services.extrusiondedicatedcta.title_part1": "Necessità di Comprimere gli Scarti Buy-to-Fly?",
    "services.extrusiondedicatedcta.subtitle": "Carica i tuoi disegni di sezione trasversale, specifiche del profilo e proiezioni di volume annuale per una rapida revisione di produzione in 24 ore — inclusa analisi di fattibilità dello stampo, strategia di lubrificazione al vetro, progettazione dell'attrezzatura isotermica, piano di raddrizzatura per stiramento e prezzi multilivello dai prototipi ai volumi di produzione completi.",
    "services.extrusiondedicatedcta.nda": "Protetto da NDA",
    "services.extrusiondedicatedcta.compliant": "Conforme ITAR / AS9100D",
    "services.extrusiondedicatedcta.response": "Risposta entro 24 Ore"
  },
  // ===== Korean (KO) =====
  ko: {
    "services.extrusionprocessspectrum.section_badge": "압출 역량",
    "services.extrusionprocessspectrum.title_part1": "티타늄 압출",
    "services.extrusionprocessspectrum.subtitle": "복잡한 구조용 프로파일에서 심리스 두꺼운 벽 튜브, 정밀 중공 다중 채널 형상까지 — 미션 크리티컬 티타늄 부품을 위한 3가지 전문 압출 워크플로우.",
    "services.extrusionprocessspectrum.0.title": "복잡 프로파일 구조 압출",
    "services.extrusionprocessspectrum.0.subtitle": "근접 네트 연속 T, L, U & H 섹션",
    "services.extrusionprocessspectrum.0.desc": "T, L, U, H 구조 섹션에 대한 근접 네트 연속 압출 실행 — 용접 조인트나 기계식 체결구 없이 심리스 하중 지지 기체, 운송 레일, 산업용 가이드 슬라이드 제공.",
    "services.extrusionprocessspectrum.0.cap0": "복잡한 비대칭 구조 프로파일의 근접 네트 압출",
    "services.extrusionprocessspectrum.0.cap1": "동시 다중 프로파일 생산을 위한 멀티 캐비티 다이 설계",
    "services.extrusionprocessspectrum.0.cap2": "전체 12,000mm 압출 길이에 걸친 일관된 벽 두께",
    "services.extrusionprocessspectrum.0.cap3": "치수 안정성을 위한 압출 후 스트레치 교정",
    "services.extrusionprocessspectrum.1.title": "심리스 두꺼운 벽 튜브",
    "services.extrusionprocessspectrum.1.subtitle": "고압 모놀리식 해저 배관 하우징",
    "services.extrusionprocessspectrum.1.desc": "세로 용접선이 없는 고압 모놀리식 해저 배관 하우징 형성 — 용접 파이프 제조에 내재된 열영향부 미세 균열 취약성 회피.",
    "services.extrusionprocessspectrum.1.cap0": "벽 두께 4.0mm ~ 50mm 이상의 심리스 튜브 압출",
    "services.extrusionprocessspectrum.1.cap1": "맨드릴 가이드 내경 제어 ±0.5mm 이내",
    "services.extrusionprocessspectrum.1.cap2": "5,000 PSI 이상 작동 압력으로 수압 테스트 완료",
    "services.extrusionprocessspectrum.1.cap3": "세로 용접 이음매 없음 — 열영향부 제로, 용접 검사 불필요",
    "services.extrusionprocessspectrum.2.title": "정밀 중공 다중 채널 형상",
    "services.extrusionprocessspectrum.2.subtitle": "냉각 공동을 위한 맞춤형 맨드릴 구성",
    "services.extrusionprocessspectrum.2.desc": "단일 티타늄 압출 블랭크 내부에 여러 냉각 공동 또는 경량 캐비티를 융합하는 맞춤형 내부 맨드릴 구성 — 압연 또는 성형 방법으로는 생산 불가.",
    "services.extrusionprocessspectrum.2.cap0": "2~8개 내부 채널을 가진 다중 보이드 중공 형상",
    "services.extrusionprocessspectrum.2.cap1": "비대칭 및 오프셋 캐비티 패턴을 위한 맞춤형 맨드릴 설계",
    "services.extrusionprocessspectrum.2.cap2": "인접 캐비티 간 일관된 벽 분할",
    "services.extrusionprocessspectrum.2.cap3": "열교환기 섹션 및 경량 구조용 빔에 이상적",
    "services.extrusionspecsdashboard.section_badge": "압출 사양",
    "services.extrusionspecsdashboard.title_part1": "압출",
    "services.extrusionspecsdashboard.subtitle": "유압 프레스 톤수, 선형 프로파일 길이, 단면 외접원 및 티타늄 압출 설비의 벽 두께 한계.",
    "services.extrusionspecsdashboard.card0.label": "압출 프레스 힘",
    "services.extrusionspecsdashboard.card0.desc": "최대 6,000미터톤까지 확장 가능한 고톤수 연속 실린더 용량 — 고온에서 복잡한 다이 형상을 통해 티타늄 빌렛을 밀어내는 데 필요한 압축력 제공.",
    "services.extrusionspecsdashboard.card1.label": "최대 선형 프로파일 길이",
    "services.extrusionspecsdashboard.card1.desc": "최대 12미터 길이의 단일 조각 연속 합금 구조 — 맞대기 용접이나 기계적 접합 없이 전체 길이 구조 프로파일 수용.",
    "services.extrusionspecsdashboard.card2.label": "단면 외접원",
    "services.extrusionspecsdashboard.card2.desc": "최대 350mm 외접원 직경의 복잡한 기하학적 외곽선 처리 — 대형 구조 프로파일, 두꺼운 벽 튜브 및 다중 채널 중공 형상 수용.",
    "services.extrusionspecsdashboard.card3.label": "구조용 벽 두께 일관성",
    "services.extrusionspecsdashboard.card3.desc": "4.0mm에서 50mm 이상 두꺼운 프로파일까지 두꺼운 단면 한계 처리 — 얇은 벽 경량 섹션에서 중하중 구조용 부재까지 포괄.",
    "services.extrusionspecsdashboard.footnote": "모든 압출은 고온(900-1050°C)에서 유리 윤활제 외피와 함께 수행됩니다. 모든 프로파일에 대해 압출 후 스트레치 교정 및 초음파 검사 가능.",
    "services.extrusionlubricationknowhow.section_badge": "공정 엔지니어링",
    "services.extrusionlubricationknowhow.title_part1": "다이 윤활 &",
    "services.extrusionlubricationknowhow.subtitle_highlight": "열 제어 노하우",
    "services.extrusionlubricationknowhow.subtitle": "티타늄의 고온 들러붙음, 다이 마모 및 선형 왜곡을 극복하려면 특수 유리 윤활과 등온 툴링 제어가 필요합니다. 항공우주 등급 압출 표면과 직진도를 달성하는 방법은 다음과 같습니다.",
    "services.extrusionlubricationknowhow.challenge": "과제",
    "services.extrusionlubricationknowhow.solution": "당사의 솔루션",
    "services.extrusionlubricationknowhow.card1.title": "고급 용융 유리 외피 윤활",
    "services.extrusionlubricationknowhow.card1.problem": "900-1050°C에서 티타늄의 열간 압출 중 극심한 압력(6,000미터톤)과 온도로 인해 티타늄 빌렛과 다이 강철 표면 사이에 심각한 접착이 발생 — 압출 프로파일 표면에 표면 찢김, 갤링 및 특징적인 '생선뼈' 물결 패턴이 생성되어 항공우주 또는 구조용 애플리케이션에 부적합하며 광범위한 압출 후 연삭 또는 폐기가 필요합니다.",
    "services.extrusionlubricationknowhow.card1.solution": "액체 경계층을 형성하는 항공우주 인증 마이크로 유리 분말 매트릭스",
    "services.extrusionlubricationknowhow.card1.detail0": "항공우주 인증 마이크로 유리 분말(입자 크기 50-200µm)을 압출 프레스에 삽입하기 전에 예열된 티타늄 빌렛에 균일 코팅으로 적용 — 유리 조성은 압출 온도(950-1050°C)에서 용융되도록 정밀하게 조제되어 빌렛과 다이 베어링 표면 사이에 연속적인 점성 액체 경계를 형성",
    "services.extrusionlubricationknowhow.card1.detail1": "용융 유리층(압출 온도에서 점도 10³-10⁵ Poise)이 10-30µm 두께의 유체 윤활막을 생성 — 티타늄을 다이 강철로부터 완전히 분리하고 표면 찢김, 갤링 및 생선뼈 물결 형성을 유발하는 금속 간 접촉을 제거",
    "services.extrusionlubricationknowhow.card1.detail2": "전체 압출 스트로크 동안 연속 윤활: 유리 코팅은 더미 블록의 저장소에서 보충되어 새로운 빌렛 재료가 다이로 공급될 때 액체 경계층을 유지 — 첫 미터에서 마지막까지 균일한 표면 품질 보장",
    "services.extrusionlubricationknowhow.card1.detail3": "결과: 압출 프레스에서 직접 Ra 1.6-3.2 µm의 표면 마감 — 표면 찢김 없음, 갤링 없음, 생선뼈 물결 없음 — 2차 표면 처리 필요성 제거 및 재료 수율 극대화",
    "services.extrusionlubricationknowhow.card2.title": "등온 툴링 사이클 & 스트레치 교정",
    "services.extrusionlubricationknowhow.card2.problem": "티타늄의 높은 압출 온도(900-1050°C)와 낮은 열전도율로 인해 압출 중 다이 표면 전체에 상당한 열 구배가 생성 — 프로파일 단면 전체에 걸쳐 차등 재료 유속이 발생하여 축 비틀림, 세로 휨 및 단면 왜곡이 발생합니다. 능동적인 열 관리와 압출 후 보정이 없으면 이러한 기하학적 결함으로 인해 긴 길이의 압출 프로파일이 구조 조립에 부적합해집니다.",
    "services.extrusionlubricationknowhow.card2.solution": "등온 유동을 위한 유도 다이 가열 루프 & 멀티톤 스트레치 교정",
    "services.extrusionlubricationknowhow.card2.detail0": "다이 홀더에 내장된 유도 가열 코일이 전체 압출 사이클 동안 다이 온도를 목표 설정점(일반적으로 950-1000°C)으로 ±5°C 정확도로 유지 — 다이가 압출물로부터 열을 전도함으로써 발생하는 점진적 냉각을 제거하여 시작부터 끝까지 균일한 금속 흐름 보장",
    "services.extrusionlubricationknowhow.card2.detail1": "다중 구역 유도 제어: 다이 중앙, 베어링 표면 및 주변의 개별 가열 구역이 독립적으로 조절 — 중앙 대비 프로파일 가장자리의 높은 열 손실을 보상하여 전체 단면에 걸쳐 균일한 재료 속도 보장 및 차등 유동 유발 비틀림 제거",
    "services.extrusionlubricationknowhow.card2.detail2": "멀티톤 유압 텐션 베드에서 압출 후 스트레치 교정: 압출 프로파일을 양 끝에서 잡고 제어된 인장 하중(일반적으로 1-3% 영구 신장)을 가함 — 이 소성 변형은 축 비틀림, 세로 휨 및 단면 왜곡을 제거하면서 직진도를 ±0.5mm/m 이내로 개선",
    "services.extrusionlubricationknowhow.card2.detail3": "결과: 직진도 ±0.5mm/m 이내, 비틀림 없음, 치수 적합한 압출 프로파일 납품 — 2차 교정이나 재작업 없이 구조 조립에 직접 통합 가능",
    "services.extrusiondedicatedcta.section_badge": "24시간 압출 타당성 검토",
    "services.extrusiondedicatedcta.title_part1": "Buy-to-Fly 스크랩을 줄여야 하나요?",
    "services.extrusiondedicatedcta.subtitle": "단면 도면, 프로파일 사양 및 연간 물량 예측을 업로드하여 신속한 24시간 제조 검토를 받으십시오 — 다이 타당성 분석, 유리 윤활 전략, 등온 툴링 설계, 스트레치 교정 계획 및 프로토타입부터 전체 생산 물량까지의 멀티티어 가격 책정이 포함됩니다.",
    "services.extrusiondedicatedcta.nda": "NDA 보호",
    "services.extrusiondedicatedcta.compliant": "ITAR / AS9100D 준수",
    "services.extrusiondedicatedcta.response": "24시간 이내 응답"
  },
  // ===== Dutch (NL) =====
  nl: {
    "services.extrusionprocessspectrum.section_badge": "Extrusiemogelijkheden",
    "services.extrusionprocessspectrum.title_part1": "Titanium extrusie",
    "services.extrusionprocessspectrum.subtitle": "Van complexe structurele profielen tot naadloze dikwandige buizen en precisie holle meerkanaalsvormen — drie gespecialiseerde extrusieworkflows voor missiekritische titaniumcomponenten.",
    "services.extrusionprocessspectrum.0.title": "Complexe profiel structurele extrusie",
    "services.extrusionprocessspectrum.0.subtitle": "Bijna-net continue T-, L-, U- & H-profielen",
    "services.extrusionprocessspectrum.0.desc": "Uitvoeren van bijna-net continue extrusie voor T-, L-, U- en H-structuursecties — leveren van naadloze dragende vliegtuigrompen, transportrails en industriële geleidingsschuiven zonder lasverbindingen of mechanische bevestigingen.",
    "services.extrusionprocessspectrum.0.cap0": "Bijna-net extrusie van complexe asymmetrische structurele profielen",
    "services.extrusionprocessspectrum.0.cap1": "Multi-holte matrijsontwerpen voor gelijktijdige multi-profielproductie",
    "services.extrusionprocessspectrum.0.cap2": "Consistente wanddikte over de volledige 12.000 mm geëxtrudeerde lengte",
    "services.extrusionprocessspectrum.0.cap3": "Rek-rechtzetten na extrusie voor dimensionale stabiliteit",
    "services.extrusionprocessspectrum.1.title": "Naadloze dikwandige buizen",
    "services.extrusionprocessspectrum.1.subtitle": "Hogedruk monolithische onderzeese leidingsystemen",
    "services.extrusionprocessspectrum.1.desc": "Vormen van hogedruk monolithische onderzeese leidingsystemen zonder longitudinale laslijnen — vermijden van de inherente microscheurgevoeligheid in de warmte-beïnvloede zone bij gelaste buizen.",
    "services.extrusionprocessspectrum.1.cap0": "Naadloze buisextrusie met wanddikte van 4,0 mm tot 50+ mm",
    "services.extrusionprocessspectrum.1.cap1": "Dorn-geleide binnendiametercontrole binnen ±0,5 mm",
    "services.extrusionprocessspectrum.1.cap2": "Hydrostatisch getest op 5.000+ PSI werkdruk",
    "services.extrusionprocessspectrum.1.cap3": "Geen longitudinale lasnaad — geen warmte-beïnvloede zone, geen lasinspectie vereist",
    "services.extrusionprocessspectrum.2.title": "Precisie holle meerkanaalsvormen",
    "services.extrusionprocessspectrum.2.subtitle": "Aangepaste dornconfiguraties voor koelholtes",
    "services.extrusionprocessspectrum.2.desc": "Aangepaste interne dornconfiguraties om meerdere koelholtes of gewichtsbesparende caviteiten in één titanium extrusieblanco te versmelten — onmogelijk te produceren met wals- of vormmethoden.",
    "services.extrusionprocessspectrum.2.cap0": "Multi-holte holle vormen met 2-8 interne kanalen",
    "services.extrusionprocessspectrum.2.cap1": "Aangepaste dornontwerpen voor asymmetrische en verschoven caviteitspatronen",
    "services.extrusionprocessspectrum.2.cap2": "Consistente wandverdeling tussen aangrenzende caviteiten",
    "services.extrusionprocessspectrum.2.cap3": "Ideaal voor warmtewisselaarsecties en lichtgewicht constructiebalken",
    "services.extrusionspecsdashboard.section_badge": "Extrusiespecificaties",
    "services.extrusionspecsdashboard.title_part1": "Extrusie",
    "services.extrusionspecsdashboard.subtitle": "Hydraulische perscapaciteit, maximale profiellengte, doorsnede-omhulling en wanddiktegrenzen van onze titanium extrusiefaciliteit.",
    "services.extrusionspecsdashboard.card0.label": "Extrusieperskracht",
    "services.extrusionspecsdashboard.card0.desc": "Hoge tonnage continue cilindercapaciteit tot 6.000 metrische ton — leveren van de drukkracht die nodig is om titanium blokken door complexe matrijsgeometrieën bij verhoogde temperaturen te persen.",
    "services.extrusionspecsdashboard.card1.label": "Maximale lineaire profiellengte",
    "services.extrusionspecsdashboard.card1.desc": "Enkelstuks ononderbroken legeringsstructuren tot 12 meter lengte — accommoderen van volledige lengte constructieprofielen zonder stomplassen of mechanische verbinding.",
    "services.extrusionspecsdashboard.card2.label": "Doorsnede omgeschreven cirkel",
    "services.extrusionspecsdashboard.card2.desc": "Omgaan met complexe geometrische omhullingen tot 350 mm omgeschreven cirkeldiameter — accommoderen van grote constructieprofielen, dikwandige buizen en meerkanaals holle vormen.",
    "services.extrusionspecsdashboard.card3.label": "Structurele wandconsistentie",
    "services.extrusionspecsdashboard.card3.desc": "Behandelen van dikke sectielimieten van 4,0 mm tot zware 50+ mm profielen — van dunwandige lichte secties tot zware dragende constructie-elementen.",
    "services.extrusionspecsdashboard.footnote": "Alle extrusie uitgevoerd bij verhoogde temperaturen (900-1050°C) met glas-smeermiddelomhulsels. Rek-rechtzetten na extrusie en ultrasone inspectie beschikbaar op alle profielen.",
    "services.extrusionlubricationknowhow.section_badge": "Procesengineering",
    "services.extrusionlubricationknowhow.title_part1": "Matrijssmering &",
    "services.extrusionlubricationknowhow.subtitle_highlight": "Thermische Controle",
    "services.extrusionlubricationknowhow.subtitle": "Het overwinnen van titanium's hechting bij hoge temperatuur, matrijsslijtage en lineaire vervorming vereist gespecialiseerde glassmering en isothermische gereedschapsregeling. Hier is hoe we extruderen oppervlakken en rechtlijnigheid van luchtvaartkwaliteit bereiken.",
    "services.extrusionlubricationknowhow.challenge": "De Uitdaging",
    "services.extrusionlubricationknowhow.solution": "Onze Oplossing",
    "services.extrusionlubricationknowhow.card1.title": "Geavanceerde gesmolten glasomhulling smering",
    "services.extrusionlubricationknowhow.card1.problem": "Tijdens het warm extruderen van titanium bij 900-1050°C veroorzaken de extreme druk (6.000 metrische ton) en temperatuur ernstige hechting tussen de titanium staaf en het matrijsstalen oppervlak — wat leidt tot scheuroppervlakken, koudruwheid en karakteristieke 'visgraat' golfpatronen op het geëxtrudeerde profiel waardoor het oppervlak ongeschikt wordt voor luchtvaart- of structurele toepassingen en uitgebreid slijpen of afval na extrusie vereist.",
    "services.extrusionlubricationknowhow.card1.solution": "Luchtvaart-gecertificeerde Micro-Glaskorrelmatrices Die Vloeistof Grenslagen Vormen",
    "services.extrusionlubricationknowhow.card1.detail0": "Luchtvaart-gecertificeerd micro-glaskorrel (deeltjesgrootte 50-200 µm) aangebracht als een uniforme coating op de voorverwarmde titanium staaf vóór plaatsing in de extrusiepers — de glassamenstelling is precies geformuleerd om te smelten bij extrusietemperatuur (950-1050°C), wat een continue viskeuze vloeistofgrens vormt tussen de staaf en het lageroppervlak van de matrijs",
    "services.extrusionlubricationknowhow.card1.detail1": "De gesmolten glaslaag (viscositeit 10³-10⁵ Poise bij extrusietemperatuur) creëert een hydrodynamische smeerfilm van 10-30 µm dik — waardoor het titanium volledig van het matrijsstaal wordt geïsoleerd en metaal-op-metaal contact wordt geëlimineerd dat oppervlaktescheuren, koudruwheid en visgraatgolfvorming veroorzaakt",
    "services.extrusionlubricationknowhow.card1.detail2": "Continue smering gedurende de gehele extrusieslag: de glascoating wordt aangevuld vanuit een reservoir in het dummyblok, waardoor de vloeistofgrenswaarde behouden blijft terwijl vers staafmateriaal in de matrijs wordt gevoerd — uniforme oppervlaktekwaliteit van de eerste tot de laatste meter",
    "services.extrusionlubricationknowhow.card1.detail3": "Resultaat: oppervlakteafwerking Ra 1,6-3,2 µm direct uit de extrusiepers — geen oppervlaktescheuren, geen koudruwheid, geen visgraatgolven — eliminatie van secundaire oppervlaktebehandeling en maximale materiaalopbrengst",
    "services.extrusionlubricationknowhow.card2.title": "Isotherme gereedschapscycli & rek-rechtzetten",
    "services.extrusionlubricationknowhow.card2.problem": "De hoge extrusietemperatuur van titanium (900-1050°C) en lage thermische geleidbaarheid creëren significante thermische gradiënten over het matrijsoppervlak tijdens extrusie — wat differentiële materiaalstroomsnelheden over de profieldoorsnede veroorzaakt die leiden tot axiale twist, longitudinale buiging en dwarsdoorsnedevervorming. Zonder actief thermisch beheer en correctie na extrusie maken deze geometrische defecten lange geëxtrudeerde profielen ongeschikt voor structurele montage.",
    "services.extrusionlubricationknowhow.card2.solution": "Inductieve Matrijsverwarmingslussen voor Isotherme Stroming & Multiton Rek-rechtzetten",
    "services.extrusionlubricationknowhow.card2.detail0": "Inductieve verwarmingsspoelen ingebed in de matrijshouder houden de matrijstemperatuur op het doelinstelpunt (typisch 950-1000°C) met ±5°C nauwkeurigheid gedurende de gehele extrusiecyclus — elimineren van de progressieve koeling die anders zou optreden terwijl de matrijs warmte van de extrusie afvoert, wat zorgt voor uniforme metaalstroom van begin tot eind",
    "services.extrusionlubricationknowhow.card2.detail1": "Multizone inductieve regeling: individuele verwarmingszones bij het matrijsoppervlak, lageroppervlak en periferie worden onafhankelijk geregeld — compenseren van het hogere warmteverlies aan de profielranden versus het midden, wat zorgt voor uniforme materiaalsnelheid over de gehele doorsnede en differentiële stromingsgeïnduceerde twist elimineert",
    "services.extrusionlubricationknowhow.card2.detail2": "Rek-rechtzetten na extrusie op een multiton hydraulische trekbank: het geëxtrudeerde profiel wordt aan beide uiteinden vastgegrepen en onderworpen aan een gecontroleerde trekbelasting (typisch 1-3% permanente verlenging) — deze plastische vervorming verwijdert axiale twist, longitudinale buiging en dwarsdoorsnedevervorming terwijl de rechtlijnigheid wordt verbeterd tot binnen ±0,5 mm/m",
    "services.extrusionlubricationknowhow.card2.detail3": "Resultaat: geëxtrudeerde profielen geleverd met rechtlijnigheid binnen ±0,5 mm/m, twistvrij en dimensionaal conform — klaar voor directe integratie in constructieassemblages zonder secundair rechtzetten of nabewerking",
    "services.extrusiondedicatedcta.section_badge": "24-Uurs Extrusie Haalbaarheidsbeoordeling",
    "services.extrusiondedicatedcta.title_part1": "Moet u Buy-to-Fly Afval Verminderen?",
    "services.extrusiondedicatedcta.subtitle": "Upload uw doorsnedetekeningen, profielspecificaties en jaarvolume projecties voor een snelle 24-uurs productiebeoordeling — inclusief matrijs haalbaarheidsanalyse, glassmeringsstrategie, isothermisch gereedschapsontwerp, rek-rechtzettingsplan en multi-tier prijzen van prototypes tot volledige productievolumes.",
    "services.extrusiondedicatedcta.nda": "NDA Beschermd",
    "services.extrusiondedicatedcta.compliant": "ITAR / AS9100D Conform",
    "services.extrusiondedicatedcta.response": "Reactie Binnen 24 Uur"
  },
  // ===== Polish (PL) =====
  pl: {
    "services.extrusionprocessspectrum.section_badge": "Zdolności wyciskania",
    "services.extrusionprocessspectrum.title_part1": "Wyciskanie tytanu",
    "services.extrusionprocessspectrum.subtitle": "Od złożonych profili konstrukcyjnych po bezszwowe grubościenne rury i precyzyjne puste kształty wielokanałowe — trzy specjalistyczne przepływy pracy wyciskania dla krytycznych komponentów tytanowych.",
    "services.extrusionprocessspectrum.0.title": "Wyciskanie złożonych profili konstrukcyjnych",
    "services.extrusionprocessspectrum.0.subtitle": "Ciągłe profile T, L, U i H o kształcie zbliżonym do gotowego",
    "services.extrusionprocessspectrum.0.desc": "Wykonywanie ciągłego wyciskania profili o kształcie zbliżonym do gotowego dla profili konstrukcyjnych T, L, U i H — dostarczanie bezszwowych, nośnych konstrukcji płatowców, szyn transportowych i przemysłowych prowadnic ślizgowych bez połączeń spawanych ani łączników mechanicznych.",
    "services.extrusionprocessspectrum.0.cap0": "Wyciskanie profili o kształcie zbliżonym do gotowego złożonych asymetrycznych profili konstrukcyjnych",
    "services.extrusionprocessspectrum.0.cap1": "Konstrukcje matryc wielownękowych do jednoczesnej produkcji wielu profili",
    "services.extrusionprocessspectrum.0.cap2": "Stała grubość ścianki na całej długości wyciskania 12 000 mm",
    "services.extrusionprocessspectrum.0.cap3": "Prostowanie przez rozciąganie po wyciskaniu dla stabilności wymiarowej",
    "services.extrusionprocessspectrum.1.title": "Bezszwowe grubościenne rury",
    "services.extrusionprocessspectrum.1.subtitle": "Wysokociśnieniowe monolityczne obudowy rurociągów podwodnych",
    "services.extrusionprocessspectrum.1.desc": "Formowanie wysokociśnieniowych monolitycznych obudów rurociągów podwodnych bez podłużnych linii spawania — unikanie podatności na mikropęknięcia w strefie wpływu ciepła nieodłącznie związanej z produkcją rur spawanych.",
    "services.extrusionprocessspectrum.1.cap0": "Bezszwowe wyciskanie rur o grubości ścianki od 4,0 mm do 50+ mm",
    "services.extrusionprocessspectrum.1.cap1": "Kontrola średnicy wewnętrznej prowadzona przez trzpień w granicach ±0,5 mm",
    "services.extrusionprocessspectrum.1.cap2": "Próba hydrostatyczna do 5 000+ PSI ciśnienia roboczego",
    "services.extrusionprocessspectrum.1.cap3": "Brak podłużnej spoiny — zerowa strefa wpływu ciepła, brak wymaganej kontroli spawania",
    "services.extrusionprocessspectrum.2.title": "Precyzyjne puste kształty wielokanałowe",
    "services.extrusionprocessspectrum.2.subtitle": "Konfiguracje trzpieni niestandardowych dla pustek chłodzących",
    "services.extrusionprocessspectrum.2.desc": "Niestandardowe konfiguracje wewnętrznych trzpieni do łączenia wielu pustek chłodzących lub wnęk odciążających wewnątrz pojedynczego wlewka wyciskarskiego z tytanu — niemożliwe do wykonania metodami walcowania lub kształtowania.",
    "services.extrusionprocessspectrum.2.cap0": "Puste kształty wielownękowe z 2-8 kanałami wewnętrznymi",
    "services.extrusionprocessspectrum.2.cap1": "Niestandardowe konstrukcje trzpieni dla asymetrycznych i przesuniętych wzorów wnęk",
    "services.extrusionprocessspectrum.2.cap2": "Spójny podział ścianek między sąsiednimi wnękami",
    "services.extrusionprocessspectrum.2.cap3": "Idealny do sekcji wymienników ciepła i lekkich belek konstrukcyjnych",
    "services.extrusionspecsdashboard.section_badge": "Specyfikacje wyciskania",
    "services.extrusionspecsdashboard.title_part1": "Wyciskanie",
    "services.extrusionspecsdashboard.subtitle": "Tonaż prasy hydraulicznej, długość liniowa profilu, obwiednia przekroju poprzecznego i granice grubości ścianki naszego zakładu wyciskania tytanu.",
    "services.extrusionspecsdashboard.card0.label": "Siła prasy wyciskarskiej",
    "services.extrusionspecsdashboard.card0.desc": "Wysokotonażowa ciągła wydajność cylindra do 6 000 ton metrycznych — dostarczanie siły ściskającej potrzebnej do przepychania wlewków tytanowych przez złożone geometrie matryc w podwyższonych temperaturach.",
    "services.extrusionspecsdashboard.card1.label": "Maksymalna długość liniowa profilu",
    "services.extrusionspecsdashboard.card1.desc": "Jednoczęściowe nieprzerwane konstrukcje stopowe o długości do 12 metrów — mieszczące profile konstrukcyjne o pełnej długości bez spawania doczołowego ani łączenia mechanicznego.",
    "services.extrusionspecsdashboard.card2.label": "Okrąg opisany na przekroju poprzecznym",
    "services.extrusionspecsdashboard.card2.desc": "Radzenie sobie ze złożonymi obwiedniami geometrycznymi do 350 mm średnicy okręgu opisanego — mieszcząc duże profile konstrukcyjne, grubościenne rury i puste kształty wielokanałowe.",
    "services.extrusionspecsdashboard.card3.label": "Spójność ścianki konstrukcyjnej",
    "services.extrusionspecsdashboard.card3.desc": "Obsługa granic grubych przekrojów od 4,0 mm do ciężkich profili 50+ mm — obejmując cienkościenne lekkie sekcje aż do ciężkich, nośnych elementów konstrukcyjnych.",
    "services.extrusionspecsdashboard.footnote": "Wszystkie wyciskania wykonywane w podwyższonych temperaturach (900-1050°C) z otulinami smaru szklanego. Prostowanie przez rozciąganie po wyciskaniu i kontrola ultradźwiękowa dostępne dla wszystkich profili.",
    "services.extrusionlubricationknowhow.section_badge": "Inżynieria procesu",
    "services.extrusionlubricationknowhow.title_part1": "Smarowanie matrycy &",
    "services.extrusionlubricationknowhow.subtitle_highlight": "Kontrola termiczna",
    "services.extrusionlubricationknowhow.subtitle": "Przezwyciężenie wysokotemperaturowego przywierania tytanu, zużycia matrycy i odkształceń liniowych wymaga specjalistycznego smarowania szklanego i izotermicznej kontroli oprzyrządowania. Oto jak osiągamy powierzchnie wyciskane i prostoliniowość klasy lotniczej.",
    "services.extrusionlubricationknowhow.challenge": "Wyzwanie",
    "services.extrusionlubricationknowhow.solution": "Nasze rozwiązanie",
    "services.extrusionlubricationknowhow.card1.title": "Zaawansowane smarowanie otuliną ze szkła stopionego",
    "services.extrusionlubricationknowhow.card1.problem": "Podczas wyciskania na gorąco tytanu w temperaturze 900-1050°C, ekstremalne ciśnienie (6 000 ton metrycznych) i temperatura powodują silną adhezję pomiędzy wlewkiem tytanowym a powierzchnią stali matrycy — powodując rozdarcia powierzchni, zatarć i charakterystyczne wzory fal 'ościch' na wyciskanym profilu, które czynią powierzchnię nieprzydatną do zastosowań lotniczych lub konstrukcyjnych i wymagają obszernego szlifowania po wyciskaniu lub złomowania.",
    "services.extrusionlubricationknowhow.card1.solution": "Matryce z Mikroproszku Szkła Certyfikowanego dla Lotnictwa Tworzące Ciekłe Warstwy Graniczne",
    "services.extrusionlubricationknowhow.card1.detail0": "Mikroproszek szklany certyfikowany dla lotnictwa (wielkość cząstek 50-200 µm) nakładany jako jednolita powłoka na wstępnie podgrzany wlewek tytanowy przed włożeniem do prasy wyciskarskiej — skład szkła jest precyzyjnie opracowany, aby topić się w temperaturze wyciskania (950-1050°C), tworząc ciągłą lepką granicę cieczy pomiędzy wlewkiem a powierzchnią nośną matrycy",
    "services.extrusionlubricationknowhow.card1.detail1": "Warstwa stopionego szkła (lepkość 10³-10⁵ Poise w temperaturze wyciskania) tworzy hydrodynamiczny film smarny o grubości 10-30 µm — całkowicie izolując tytan od stali matrycy i eliminując kontakt metal-metal, który powoduje rozdarcia powierzchni, zatarcia i tworzenie się fal ościch",
    "services.extrusionlubricationknowhow.card1.detail2": "Ciągłe smarowanie przez cały skok wyciskania: powłoka szklana jest uzupełniana z zasobnika w bloku pozornym, utrzymując ciekłą warstwę graniczną w miarę jak świeży materiał wlewka jest podawany do matrycy — zapewniając jednolitą jakość powierzchni od pierwszego do ostatniego metra",
    "services.extrusionlubricationknowhow.card1.detail3": "Wynik: chropowatość powierzchni Ra 1,6-3,2 µm bezpośrednio z prasy wyciskarskiej — bez rozdarć powierzchni, bez zatarć, bez fal ościch — eliminując potrzebę wtórnej obróbki powierzchni i maksymalizując wydajność materiałową",
    "services.extrusionlubricationknowhow.card2.title": "Izotermiczne cykle oprzyrządowania & prostowanie przez rozciąganie",
    "services.extrusionlubricationknowhow.card2.problem": "Wysoka temperatura wyciskania tytanu (900-1050°C) i niska przewodność cieplna tworzą znaczące gradienty termiczne na powierzchni matrycy podczas wyciskania — powodując zróżnicowane prędkości przepływu materiału w przekroju poprzecznym profilu, które skutkują skręceniem osiowym, podłużnym wygięciem i zniekształceniem przekroju poprzecznego. Bez aktywnego zarządzania termicznego i korekcji po wyciskaniu, te wady geometryczne czynią długie profile wyciskane nieodpowiednimi do montażu konstrukcyjnego.",
    "services.extrusionlubricationknowhow.card2.solution": "Indukcyjne Pętle Grzewcze Matrycy dla Przepływu Izotermicznego & Wielotonowe Prostowanie przez Rozciąganie",
    "services.extrusionlubricationknowhow.card2.detail0": "Cewki grzewcze indukcyjne osadzone w uchwycie matrycy utrzymują temperaturę matrycy na docelowym punkcie zadanym (zazwyczaj 950-1000°C) z dokładnością ±5°C przez cały cykl wyciskania — eliminując postępujące chłodzenie, które w przeciwnym razie wystąpiłoby, gdy matryca odprowadza ciepło z wyciskania, zapewniając równomierny przepływ metalu od początku do końca",
    "services.extrusionlubricationknowhow.card2.detail1": "Wielostrefowa kontrola indukcyjna: poszczególne strefy grzewcze w centrum matrycy, na powierzchni nośnej i na obwodzie są regulowane niezależnie — kompensując wyższą utratę ciepła na krawędziach profilu w stosunku do środka, zapewniając równomierną prędkość materiału w całym przekroju poprzecznym i eliminując skręcenie wywołane różnicowym przepływem",
    "services.extrusionlubricationknowhow.card2.detail2": "Prostowanie przez rozciąganie po wyciskaniu na wielotonowym hydraulicznym stole naprężającym: wyciskany profil jest chwytany na obu końcach i poddawany kontrolowanemu obciążeniu rozciągającemu (zazwyczaj 1-3% trwałego wydłużenia) — to odkształcenie plastyczne usuwa skręcenie osiowe, podłużne wygięcie i zniekształcenie przekroju poprzecznego, poprawiając prostoliniowość do ±0,5 mm/m",
    "services.extrusionlubricationknowhow.card2.detail3": "Wynik: profile wyciskane dostarczane z prostoliniowością w granicach ±0,5 mm/m, bez skręcenia i zgodne wymiarowo — gotowe do bezpośredniej integracji z zespołami konstrukcyjnymi bez wtórnego prostowania lub poprawek",
    "services.extrusiondedicatedcta.section_badge": "24-godzinna ocena wykonalności wyciskania",
    "services.extrusiondedicatedcta.title_part1": "Potrzebujesz zmniejszyć odpady typu Buy-to-Fly?",
    "services.extrusiondedicatedcta.subtitle": "Prześlij swoje rysunki przekroju poprzecznego, specyfikacje profili i prognozy rocznych wolumenów w celu szybkiej 24-godzinnej oceny produkcyjnej — w tym analizy wykonalności matrycy, strategii smarowania szkłem, projektu oprzyrządowania izotermicznego, planu prostowania przez rozciąganie i wyceny wielopoziomowej od prototypów do pełnych wolumenów produkcyjnych.",
    "services.extrusiondedicatedcta.nda": "Chronione umową NDA",
    "services.extrusiondedicatedcta.compliant": "Zgodność z ITAR / AS9100D",
    "services.extrusiondedicatedcta.response": "Odpowiedź w ciągu 24 godzin"
  }
};

const langs = ['ja', 'de', 'fr', 'es', 'pt', 'it', 'ko', 'nl', 'pl'];
const en = JSON.parse(fs.readFileSync('src/i18n/translations/en.json', 'utf8'));

langs.forEach(lang => {
  const filePath = `src/i18n/translations/${lang}.json`;
  const data = JSON.parse(fs.readFileSync(filePath, 'utf8'));
  const trans = translations[lang];
  let updated = 0;

  Object.keys(trans).forEach(key => {
    if (data[key] === undefined || data[key] === en[key]) {
      data[key] = trans[key];
      updated++;
    }
  });

  fs.writeFileSync(filePath, JSON.stringify(data, null, 2) + '\n', 'utf8');
  console.log(`${lang}: ${updated} keys updated`);
});

console.log('\nAll 9 languages extrusion page translations written!');