import fs from 'fs';
const en = JSON.parse(fs.readFileSync('src/i18n/translations/en.json','utf8'));
// AI Infrastructure content keys
const keys = {
'industries.ai.optoelectronic.badge':'Optoelectronic Enclosures',
'industries.ai.optoelectronic.title.main':'Precision CNC Milling',
'industries.ai.optoelectronic.title.suffix':'800G/1.6T Optical Transceiver Housings with Thin-Wall EMI Shielding',
'industries.ai.optoelectronic.desc':'High-precision titanium optoelectronic enclosures for 800G and 1.6T optical transceivers. Thin-wall pocketing down to 0.4 mm provides natural EMI shielding while titanium\'s low CTE eliminates optical axis drift under thermal cycling.',
'industries.ai.optoelectronic.card1.title':'800G/1.6T Transceiver Housing Milling',
'industries.ai.optoelectronic.card1.subtitle':'Precision CNC · Thin-Wall 0.4mm · EMI Shielding',
'industries.ai.optoelectronic.card1.desc':'Optical transceivers operating at 800G and 1.6T require housings with thin-wall EMI shielding, precise fiber alignment features, and thermal stability. Titanium\'s inherent EMI attenuation eliminates the need for costly conductive gaskets or coatings.',
'industries.ai.optoelectronic.card1.implLabel':'Technical Implementation',
'industries.ai.optoelectronic.card1.item1':'Thin-wall pocketing to 0.4 mm wall thickness — natural EMI shielding without conductive gaskets',
'industries.ai.optoelectronic.card1.item2':'Low CTE (8.6 ppm/°C) eliminates optical misalignment under 0-70°C operating range',
'industries.ai.optoelectronic.card1.item3':'Cross-talk isolation walls machined integrally — eliminates signal interference between adjacent channels',
'industries.ai.optoelectronic.card2.title':'Fiber Alignment & Hermetic Sealing',
'industries.ai.optoelectronic.card2.subtitle':'±0.005 mm Positioning · Laser Weld Ready',
'industries.ai.optoelectronic.card2.desc':'Fiber feed-through positioning and sealing surface coplanarity determine optical coupling efficiency. Titanium\'s thermal expansion matches optical sub-component substrates, maintaining alignment from assembly through field operation.',
'industries.ai.optoelectronic.card2.implLabel':'Technical Implementation',
'industries.ai.optoelectronic.card2.item1':'Sealing surface coplanarity ≤ 0.01 mm — enables hermetic laser weld sealing per Telcordia GR-468',
'industries.ai.optoelectronic.card2.item2':'Fiber feed-through hole positioning ±0.005 mm — guarantees core-to-core optical alignment',
'industries.ai.optoelectronic.card2.item3':'Grade 2 and Grade 5 titanium options — matched to CTE requirements of specific optical sub-assemblies',
'industries.ai.optoelectronic.entity.0':'Precision CNC Milling',
'industries.ai.optoelectronic.entity.1':'800G/1.6T Transceiver Housings',
'industries.ai.optoelectronic.entity.2':'EMI Shielding',
'industries.ai.optoelectronic.entity.3':'Thermal Drift Prevention',
'industries.ai.optoelectronic.entity.4':'Thin-Wall 0.4mm',
'industries.ai.liquidcooling.badge':'Data Center Liquid Cooling',
'industries.ai.liquidcooling.title.main':'Multi-Axis CNC Machining',
'industries.ai.liquidcooling.title.suffix':'Liquid Cooling Manifolds, Cold Plates & Quick-Disconnect Valves',
'industries.ai.liquidcooling.desc':'High-precision titanium liquid cooling manifolds and cold plates for AI GPU/ASIC clusters. Corrosion-free fluid channels machined from Grade 5 Titanium — engineered for leak-proof operation under relentless thermal cycling.',
'industries.ai.liquidcooling.card1.title':'Liquid Cooling Manifolds & Cold Plates',
'industries.ai.liquidcooling.card1.subtitle':'Multi-Axis CNC · Grade 5 Ti · GPU/ASIC Clusters',
'industries.ai.liquidcooling.card1.desc':'AI training clusters generate heat densities exceeding 1000 W per GPU demanding direct-to-chip liquid cooling with absolute reliability. Our multi-axis CNC machining produces titanium manifolds and cold plates with optimized micro-channel geometries.',
'industries.ai.liquidcooling.card1.implLabel':'Technical Implementation',
'industries.ai.liquidcooling.card1.item1':'Micro-channel geometry optimized for maximum heat transfer at coolant pressures up to 10 bar',
'industries.ai.liquidcooling.card1.item2':'Titanium\'s natural corrosion resistance eliminates galvanic reactions with dielectric coolants',
'industries.ai.liquidcooling.card1.item3':'Single-piece manifold construction eliminates potential leak paths from multi-part welded assemblies',
'industries.ai.liquidcooling.card2.title':'Quick-Disconnect Valve & Fitting Manufacturing',
'industries.ai.liquidcooling.card2.subtitle':'Ra ≤ 0.4 µm Sealing · Helium Leak Tested',
'industries.ai.liquidcooling.card2.desc':'Data center liquid cooling loops require quick-disconnect valves and fittings that maintain zero-leak performance across thousands of mate-demate cycles. Our precision-turned titanium valve bodies achieve Ra ≤ 0.4 µm sealing surface finishes.',
'industries.ai.liquidcooling.card2.implLabel':'Technical Implementation',
'industries.ai.liquidcooling.card2.item1':'Sealing surface finish Ra ≤ 0.4 µm — ensures leak-proof O-ring sealing across temperature range',
'industries.ai.liquidcooling.card2.item2':'Thread forms per ASME B1.1 — consistent preload for thousands of connect-disconnect cycles',
'industries.ai.liquidcooling.card2.item3':'100% helium leak testing available — verified to < 1×10⁻⁹ mbar·L/s for critical cooling loops',
'industries.ai.liquidcooling.entity.0':'Multi-Axis CNC Machining',
'industries.ai.liquidcooling.entity.1':'Liquid Cooling Manifolds',
'industries.ai.liquidcooling.entity.2':'Cold Plates',
'industries.ai.liquidcooling.entity.3':'Quick-Disconnect Valves',
'industries.ai.liquidcooling.entity.4':'Grade 5 Ti-6Al-4V',
'industries.ai.metrology.badge':'Precision Metrology',
'industries.ai.metrology.title.main':'CMM Dimensional Validation',
'industries.ai.metrology.title.suffix':'GD&T Coplanarity & Geometric Alignment for Optical Sub-Assemblies',
'industries.ai.metrology.desc':'Absolute dimensional verification via CMM mapping to ASME Y14.5 GD&T standards guaranteeing coplanarity, flatness, and positional accuracy for high-yield fiber alignment in optical transceiver sub-assemblies.',
'industries.ai.metrology.card1.title':'CMM for Optical Component Verification',
'industries.ai.metrology.card1.subtitle':'ZEISS CMM · ±1.9 µm · ASME Y14.5 GD&T',
'industries.ai.metrology.card1.desc':'Optical transceiver housings and liquid cooling manifolds demand micron-level geometric precision. Our ZEISS CMM platforms measure flatness, parallelism, true position, and profile tolerances across all sealing surfaces.',
'industries.ai.metrology.card1.implLabel':'Technical Implementation',
'industries.ai.metrology.card1.item1':'ZEISS CMM ±1.9 µm volumetric accuracy — ISO 17025 traceable calibration for optical components',
'industries.ai.metrology.card1.item2':'Sealing surface coplanarity ≤ 0.01 mm — ensures consistent laser weld hermeticity',
'industries.ai.metrology.card1.item3':'Full GD&T reporting per ASME Y14.5 — flatness, parallelism, profile, true position on every lot',
'industries.ai.metrology.card2.title':'GD&T for High-Yield Assembly',
'industries.ai.metrology.card2.subtitle':'True Position ±0.01mm · Flatness ≤0.005mm/25mm',
'industries.ai.metrology.card2.desc':'Sub-micron geometric tolerances on optical transceiver housings directly determine optical coupling efficiency and manufacturing yield. Our GD&T verification culture ensures every component meets ASME Y14.5 specifications.',
'industries.ai.metrology.card2.implLabel':'Technical Implementation',
'industries.ai.metrology.card2.item1':'True position ≤ ±0.01 mm for fiber array and laser diode mounting features',
'industries.ai.metrology.card2.item2':'Surface flatness ≤ 0.005 mm per 25 mm — ensures PCB and sub-mount seating without stress',
'industries.ai.metrology.card2.item3':'SPC trending for production monitoring — early detection of tool wear or thermal drift',
'industries.ai.metrology.entity.0':'CMM (Coordinate Measuring Machine)',
'industries.ai.metrology.entity.1':'ASME Y14.5 GD&T',
'industries.ai.metrology.entity.2':'Coplanarity',
'industries.ai.metrology.entity.3':'Fiber Alignment',
'industries.ai.metrology.entity.4':'ZEISS CMM',
'industries.ai.compliance.badge':'Material Certification',
'industries.ai.compliance.title.main':'Material Traceability',
'industries.ai.compliance.title.suffix':'EN 10204 3.1 MTR & Heat Number Tracking for Mission-Critical Infrastructure',
'industries.ai.compliance.desc':'Every AI infrastructure component is backed by EN 10204 3.1 Mill Test Reports and laser-marked heat numbers validating metallurgical purity to prevent invisible micro-cracks in 24/7 data center server matrices.',
'industries.ai.compliance.pillar1.title':'EN 10204 3.1 MTR & Heat Number',
'industries.ai.compliance.pillar1.desc':'Every batch of Grade 2, Grade 5, and specialty titanium is certified with EN 10204 Type 3.1 documentation verifying chemical composition and mechanical properties.',
'industries.ai.compliance.pillar1.item1':'Chemical composition per ASTM B265/B348 — verified for purity and interstitial element control',
'industries.ai.compliance.pillar1.item2':'Laser-marked heat number on each component — permanent traceability to mill certification',
'industries.ai.compliance.pillar1.item3':'Digital MTR archive — full traceability chain from raw material to finished component',
'industries.ai.compliance.pillar2.title':'Reliability for 24/7 Uptime',
'industries.ai.compliance.pillar2.desc':'Data center cooling and optical infrastructure operates 24/7/365 — component failure is not an option. Our strict material verification and processing controls eliminate the risk of invisible micro-cracks or metallurgical defects.',
'industries.ai.compliance.pillar2.item1':'100% material verification before machining — eliminates hidden defects in critical cooling paths',
'industries.ai.compliance.pillar2.item2':'Dye penetrant inspection available — verifies surface integrity on pressure-containing components',
'industries.ai.compliance.pillar2.item3':'Full traceability chain — raw material heat lot to machining to cleaning to delivery',
'industries.ai.compliance.entity.0':'EN 10204 3.1 MTR',
'industries.ai.compliance.entity.1':'Heat Number',
'industries.ai.compliance.entity.2':'Metallurgical Purity',
'industries.ai.compliance.entity.3':'Dye Penetrant',
'industries.ai.compliance.entity.4':'24/7 Uptime',
};
// Entity label keys
keys['industries.ai.optoelectronic.entityLabel'] = 'Entity Cluster';
keys['industries.ai.liquidcooling.entityLabel'] = 'Entity Cluster';
keys['industries.ai.metrology.entityLabel'] = 'Entity Cluster';
keys['industries.ai.compliance.entityLabel'] = 'Entity Cluster';

let n = 0;
for (const [k,v] of Object.entries(keys)) { if (!en[k]) { en[k] = v; n++; } }
const s = {}; Object.keys(en).sort().forEach(k => { s[k] = en[k]; });
fs.writeFileSync('src/i18n/translations/en.json', JSON.stringify(s,null,2)+'\n','utf8');
console.log('Added '+n+' AI Infrastructure keys');
